-- name: InsertAuditEvent :exec
-- Append-only INSERT (the audit_events slice has NO read / update / delete
-- surface). occurred_at is deliberately OMITTED so the DB DEFAULT now()
-- (transaction time) applies; the emitting write path does not supply a
-- client clock. id is the uuid.NewV7 generated by the emitting write path.
-- actor_id is sqlc.narg (nullable): 'user' events carry the actor's
-- users.id; 'system' events (not emitted this slice) carry SQL NULL.
INSERT INTO audit_events (id, actor_id, actor_type, event_type, entity_type, entity_id, metadata)
VALUES (
    sqlc.arg('id')::uuid,
    sqlc.narg('actor_id')::uuid,
    sqlc.arg('actor_type')::text,
    sqlc.arg('event_type')::text,
    sqlc.arg('entity_type')::text,
    sqlc.arg('entity_id')::uuid,
    sqlc.arg('metadata')::jsonb
);
