// Package entities holds the applications bounded-context domain entities.
//
// The applications slice is the bridge between candidates and jobs: a
// candidate applies to a published job via a single atomic SQL gate, and a
// recruiter of the owning company manages the resulting row through a
// three-step pipeline. The entity layer is the persistence-port
// projection surface — it has no IO, no factory (UUIDs are generated by the
// use case), and never imports `internal/db` (mirrors the jobs slice
// boundary). VOs for the closed-set columns are reconstructed via
// `valueobjects.Parse*` so an unrecognized DB value fails loud rather than
// silently zeroing.
package entities

import (
	"errors"
	"time"

	"github.com/aldrichcode45/peopleflow-vacantes/internal/features/applications/domain/valueobjects"
	"github.com/google/uuid"
)

// Application-domain sentinel errors. The 7 sentinels are pairwise distinct
// so the HTTP classifier can dispatch on a single errors.Is chain.
//
// Mapping to HTTP status codes (the classifier lives in
// `infrastructure/http/applicationHandler.go`):
//
//	ErrApplicationNotFound         → 404 "application not found"
//	ErrJobNotApplicable            → 404 "job not applicable"
//	ErrAlreadyApplied              → 409 "already applied"
//	ErrInvalidApplicationReference → 400 "invalid application reference"
//	ErrCoverLetterEmpty            → 400 "cover_letter must not be empty"
//	ErrCoverLetterTooLong          → 400 "cover_letter must be at most 2000 characters"
//	ErrStatusRequired              → 400 "status is required"
var (
	ErrApplicationNotFound         = errors.New("application not found")
	ErrJobNotApplicable            = errors.New("job not applicable")
	ErrAlreadyApplied              = errors.New("already applied")
	ErrInvalidApplicationReference = errors.New("invalid application reference")
	ErrCoverLetterEmpty            = errors.New("cover_letter must not be empty")
	ErrCoverLetterTooLong          = errors.New("cover_letter must be at most 2000 characters")
	ErrStatusRequired              = errors.New("status is required")
)

// Application is the persisted job-application row. The struct carries
// every column from the `applications` table the domain layer is willing to
// hand to a caller (the postgres adapter is the sole translator).
//
// Optional columns (Source, CoverLetter) surface as pointers so SQL NULL
// is distinguishable from a real zero value. cv_s3_key and anonymized_at
// are deliberately NOT in this struct — they are reserved columns that
// the slice never reads or writes; surfacing them would let a future
// caller smuggle them into a DTO.
type Application struct {
	ID          uuid.UUID
	JobID       uuid.UUID
	CandidateID uuid.UUID
	Status      valueobjects.ApplicationStatus

	// Source is the optional closed-set classification (referral/linkedin/etc).
	Source *valueobjects.ApplicationSource
	// CoverLetter is the optional trimmed cover letter text (≤ 2000 runes).
	CoverLetter *string

	CreatedAt time.Time
	UpdatedAt time.Time
}

// CandidateSnippet is the PII-minimized candidate projection the
// recruiter list + detail endpoints embed. Only `users.full_name` plus
// `candidate_profiles.{professional_title, years_of_experience}` — NO
// salary, birth_date, phone, email, skills, languages, expected_salary,
// education_level, city, address, or bio (design D12).
type CandidateSnippet struct {
	UserID            uuid.UUID
	FullName          string
	ProfessionalTitle *string
	YearsOfExperience *int
}

// JobSummary is the candidate's thin pointer back to the job in the
// `/me/applications` list — id + title + the owning company's id/name.
// Other job fields (description, salary_*, work_mode, employment_type,
// seniority, location, published_at, deleted_at, status) are deliberately
// omitted; the public `GET /jobs/{id}` is the source of truth for those.
type JobSummary struct {
	ID          uuid.UUID
	Title       string
	CompanyID   uuid.UUID
	CompanyName string
}

// ApplicationWithCandidate is the recruiter-facing projection: an
// Application plus the PII-minimized CandidateSnippet. It is what
// `ListByJob` and `GetByID` return.
type ApplicationWithCandidate struct {
	Application
	Candidate CandidateSnippet
}

// MyApplication is the candidate-facing projection: an Application plus
// the JobSummary pointer. It is what `ListByCandidate` returns.
//
// `cv_s3_key` and `anonymized_at` are intentionally absent — they are
// reserved columns that the slice never exposes to candidates (or to
// recruiters); the DTO layer must not surface them either.
type MyApplication struct {
	Application
	Job JobSummary
}
