// Package postgres implements the candidates persistence port against
// PostgreSQL. The adapter owns the *pgxpool.Pool so it can run the
// atomic language-replace in a single transaction; the *db.Queries
// generated by sqlc is scoped per-call (db.New(pool) or db.New(tx)).
package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/aldrichcode45/peopleflow-vacantes/internal/db"
	"github.com/aldrichcode45/peopleflow-vacantes/internal/features/candidates/domain/entities"
	candidaterepositories "github.com/aldrichcode45/peopleflow-vacantes/internal/features/candidates/domain/repositories"
	"github.com/aldrichcode45/peopleflow-vacantes/internal/features/candidates/domain/valueobjects"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

// CandidateRepository is the PostgreSQL adapter for
// candidaterepositories.CandidateRepository. It holds a connection pool
// because the atomic language-replace needs to manage its own
// transaction; non-tx paths borrow a Queries from db.New(pool).
type CandidateRepository struct {
	pool *pgxpool.Pool
}

// NewCandidateRepository wraps the connection pool. The pool is
// retained so the adapter can open transactions directly via
// pool.Begin(ctx).
func NewCandidateRepository(pool *pgxpool.Pool) *CandidateRepository {
	return &CandidateRepository{pool: pool}
}

// Compile-time assertion that the adapter satisfies the domain port.
// A future port change here surfaces as a build error, never a runtime
// "method missing" panic.
var _ candidaterepositories.CandidateRepository = (*CandidateRepository)(nil)

// UpsertProfile performs the idempotent INSERT ... ON CONFLICT (user_id)
// DO UPDATE on candidate_profiles and returns the persisted row. The
// search_vector column is a STORED generated column owned by Postgres
// and MUST NOT be touched from application code (design decision #9).
func (r *CandidateRepository) UpsertProfile(ctx context.Context, profile *entities.CandidateProfile) (*entities.CandidateProfile, error) {
	row, err := db.New(r.pool).UpsertCandidateProfile(ctx, buildUpsertParams(profile))
	if err != nil {
		return nil, mapCreateError(err)
	}
	return toEntity(row)
}

// GetProfileByUserID fetches the caller's profile. The pgx "no rows"
// sentinel is translated to entities.ErrProfileNotFound so the HTTP
// layer can dispatch on errors.Is without importing pgx.
func (r *CandidateRepository) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (*entities.CandidateProfile, error) {
	row, err := db.New(r.pool).GetCandidateProfileByUserID(ctx, userID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, entities.ErrProfileNotFound
		}
		return nil, err
	}
	return toEntity(row)
}

// ListLanguagesByUserID returns the caller's candidate_languages rows
// ordered by language. An empty list comes back as a non-nil empty
// slice so the JSON encoder produces "[]" rather than "null".
func (r *CandidateRepository) ListLanguagesByUserID(ctx context.Context, userID uuid.UUID) ([]entities.Language, error) {
	rows, err := db.New(r.pool).ListCandidateLanguagesByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}
	out := make([]entities.Language, 0, len(rows))
	for _, row := range rows {
		level, err := valueobjects.ParseCefrLevel(row.Level)
		if err != nil {
			// A row that survived a past migration with a bad level is
			// a real data-integrity issue; fail loud rather than
			// silently substituting UnknownCefrLevel.
			return nil, fmt.Errorf("invalid CEFR level in candidate_languages: %w", err)
		}
		out = append(out, entities.Language{Name: row.Language, Level: level})
	}
	return out, nil
}

// ReplaceLanguagesByUserID atomically replaces the user's full
// language list. The delete + N inserts run in one pgx.Tx so a
// duplicate (or any other error) rolls the whole operation back,
// leaving the original list intact. The composite PK (user_id,
// language) is the second line of defense after the use case's
// duplicate check.
func (r *CandidateRepository) ReplaceLanguagesByUserID(ctx context.Context, userID uuid.UUID, languages []entities.Language) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	// defer Rollback is a no-op after Commit succeeds; on any error
	// path below it sends the ROLLBACK to the server.
	defer func() { _ = tx.Rollback(ctx) }()

	queries := db.New(tx)
	if err := queries.DeleteCandidateLanguagesByUserID(ctx, userID); err != nil {
		return fmt.Errorf("delete existing languages: %w", err)
	}

	for _, l := range languages {
		if err := queries.InsertCandidateLanguage(ctx, db.InsertCandidateLanguageParams{
			UserID:   userID,
			Language: l.Name,
			Level:    l.Level.String(),
		}); err != nil {
			// The unique PK (user_id, language) catches any duplicate
			// the use case let through; surface a domain sentinel so
			// the HTTP layer can map to 400.
			return mapCreateError(err)
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit tx: %w", err)
	}
	return nil
}

// buildUpsertParams translates the entity into the sqlc parameter
// struct. Every optional field becomes an invalid pgtype (SQL NULL)
// when the entity pointer is nil so the DB CHECK constraints see the
// same shape the domain validation produced.
func buildUpsertParams(p *entities.CandidateProfile) db.UpsertCandidateProfileParams {
	var birthDate pgtype.Date
	if p.BirthDate != nil {
		birthDate = pgtype.Date{Time: *p.BirthDate, Valid: true}
	}
	return db.UpsertCandidateProfileParams{
		UserID:               uuid.MustParse(p.UserID),
		Phone:                textPtrToPgText(p.Phone),
		LinkedinUrl:          textPtrToPgText(p.LinkedInURL),
		PortfolioUrl:         textPtrToPgText(p.PortfolioURL),
		ProfessionalTitle:    textPtrToPgText(p.ProfessionalTitle),
		CurrentCompany:       textPtrToPgText(p.CurrentCompany),
		YearsOfExperience:    intPtrToInt2(p.YearsOfExperience),
		ProfileSummary:       textPtrToPgText(p.ProfileSummary),
		BirthDate:            birthDate,
		City:                 textPtrToPgText(p.City),
		Country:              textPtrToPgText(p.Country),
		EducationLevel:       educationLevelToPgText(p.EducationLevel),
		FieldOfStudy:         textPtrToPgText(p.FieldOfStudy),
		Skills:               p.Skills,
		CurrentSalaryGross:   intPtrToInt4(p.CurrentSalaryGross),
		CurrentSalaryNet:     intPtrToInt4(p.CurrentSalaryNet),
		ExpectedSalary:       intPtrToInt4(p.ExpectedSalary),
		SalaryCurrency:       p.SalaryCurrency,
		ExpectedSalaryPeriod: salaryPeriodToPgText(p.ExpectedSalaryPeriod),
		CvS3Key:              textPtrToPgText(p.CVS3Key),
	}
}

// toEntity rebuilds the domain entity from a sqlc row. VOs are
// reconstructed via their parsers so unrecognized values fail loudly
// instead of silently producing a zero-valued aggregate.
func toEntity(row db.CandidateProfile) (*entities.CandidateProfile, error) {
	var edu *valueobjects.EducationLevel
	if row.EducationLevel.Valid {
		parsed, err := valueobjects.ParseEducationLevel(row.EducationLevel.String)
		if err != nil {
			return nil, err
		}
		edu = &parsed
	}

	var period *valueobjects.SalaryPeriod
	if row.ExpectedSalaryPeriod.Valid {
		parsed, err := valueobjects.ParseSalaryPeriod(row.ExpectedSalaryPeriod.String)
		if err != nil {
			return nil, err
		}
		period = &parsed
	}

	return &entities.CandidateProfile{
		UserID:               row.UserID.String(),
		Phone:                pgTextToTextPtr(row.Phone),
		LinkedInURL:          pgTextToTextPtr(row.LinkedinUrl),
		PortfolioURL:         pgTextToTextPtr(row.PortfolioUrl),
		ProfessionalTitle:    pgTextToTextPtr(row.ProfessionalTitle),
		CurrentCompany:       pgTextToTextPtr(row.CurrentCompany),
		YearsOfExperience:    int2ToIntPtr(row.YearsOfExperience),
		ProfileSummary:       pgTextToTextPtr(row.ProfileSummary),
		BirthDate:            pgDateToTimePtr(row.BirthDate),
		City:                 pgTextToTextPtr(row.City),
		Country:              pgTextToTextPtr(row.Country),
		EducationLevel:       edu,
		FieldOfStudy:         pgTextToTextPtr(row.FieldOfStudy),
		Skills:               row.Skills,
		CurrentSalaryGross:   int4ToIntPtr(row.CurrentSalaryGross),
		CurrentSalaryNet:     int4ToIntPtr(row.CurrentSalaryNet),
		ExpectedSalary:       int4ToIntPtr(row.ExpectedSalary),
		SalaryCurrency:       row.SalaryCurrency,
		ExpectedSalaryPeriod: period,
		CVS3Key:              pgTextToTextPtr(row.CvS3Key),
		CreatedAt:            pgTimestamptzToTime(row.CreatedAt),
		UpdatedAt:            pgTimestamptzToTime(row.UpdatedAt),
	}, nil
}

// --- pgtype ↔ Go pointer helpers ----------------------------------------

func textPtrToPgText(s *string) pgtype.Text {
	if s == nil {
		return pgtype.Text{}
	}
	return pgtype.Text{String: *s, Valid: true}
}

func pgTextToTextPtr(t pgtype.Text) *string {
	if !t.Valid {
		return nil
	}
	v := t.String
	return &v
}

func intPtrToInt2(i *int) pgtype.Int2 {
	if i == nil {
		return pgtype.Int2{}
	}
	return pgtype.Int2{Int16: int16(*i), Valid: true}
}

func int2ToIntPtr(i pgtype.Int2) *int {
	if !i.Valid {
		return nil
	}
	v := int(i.Int16)
	return &v
}

func intPtrToInt4(i *int) pgtype.Int4 {
	if i == nil {
		return pgtype.Int4{}
	}
	return pgtype.Int4{Int32: int32(*i), Valid: true}
}

func int4ToIntPtr(i pgtype.Int4) *int {
	if !i.Valid {
		return nil
	}
	v := int(i.Int32)
	return &v
}

func pgDateToTimePtr(d pgtype.Date) *time.Time {
	if !d.Valid {
		return nil
	}
	v := d.Time
	return &v
}

func pgTimestamptzToTime(t pgtype.Timestamptz) time.Time {
	if !t.Valid {
		return time.Time{}
	}
	return t.Time
}

func educationLevelToPgText(e *valueobjects.EducationLevel) pgtype.Text {
	if e == nil {
		return pgtype.Text{}
	}
	return pgtype.Text{String: e.String(), Valid: true}
}

func salaryPeriodToPgText(s *valueobjects.SalaryPeriod) pgtype.Text {
	if s == nil {
		return pgtype.Text{}
	}
	return pgtype.Text{String: s.String(), Valid: true}
}

// mapCreateError translates Postgres constraint violations into domain
// sentinels so the HTTP layer can return 4xx instead of leaking 500s
// for client errors. Mirrors the companies adapter's contract.
//
//   - pgx.ErrNoRows → ErrProfileNotFound (Get path)
//   - 23505 (any UNIQUE collision) → ErrDuplicateLanguage
//   - anything else → pass through unchanged
//
// The (user_id, language) composite PK on candidate_languages is the
// only UNIQUE constraint this adapter can trip. The candidate_profiles
// PK on user_id cannot collide under ON CONFLICT DO UPDATE.
func mapCreateError(err error) error {
	if err == nil {
		return nil
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return entities.ErrProfileNotFound
	}
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == "23505" { // unique_violation
		return entities.ErrDuplicateLanguage
	}
	return err
}
