-- +goose Up
-- +goose StatementBegin
-- jobs (§spec/jobs): public-read job board table. The full status domain
-- (draft → published → closed) lives in the DB; only `status='published'`
-- rows with `deleted_at IS NULL` and an `active` owning company are exposed
-- on read (enforced in SQL, not in Go).
--
-- UUID v7 is generated by the application — no DB default on `id`. Default
-- on `status` is `draft` so every row is born hidden from the public listing.
-- `salary_currency` is NOT NULL with a DEFAULT of `'MXN'` to match the
-- `candidates` table convention and to keep the optional NULL fields to
-- `location`/`salary_min`/`salary_max`.
--
-- Integrity guard: a `status='published'` row MUST have `published_at`. The
-- CHECK `status <> 'published' OR published_at IS NOT NULL` enforces that
-- invariant at the DB boundary so a future publish flow cannot leave a row
-- visible with a NULL publish timestamp.
CREATE TABLE jobs (
    id               UUID PRIMARY KEY,
    company_id       UUID NOT NULL REFERENCES companies (id),
    title            TEXT NOT NULL,
    description      TEXT NOT NULL,
    work_mode        TEXT NOT NULL
        CONSTRAINT jobs_work_mode_check
        CHECK (work_mode IN ('onsite', 'remote', 'hybrid')),
    employment_type  TEXT NOT NULL
        CONSTRAINT jobs_employment_type_check
        CHECK (employment_type IN ('full_time', 'part_time', 'contract', 'internship')),
    seniority        TEXT NOT NULL
        CONSTRAINT jobs_seniority_check
        CHECK (seniority IN ('intern', 'junior', 'mid', 'senior', 'lead')),
    status           TEXT NOT NULL DEFAULT 'draft'
        CONSTRAINT jobs_status_check
        CHECK (status IN ('draft', 'published', 'closed')),
    location         TEXT,
    salary_min       INTEGER,
    salary_max       INTEGER,
    salary_currency  TEXT NOT NULL DEFAULT 'MXN'
        CONSTRAINT jobs_salary_currency_check
        CHECK (salary_currency IN ('USD', 'MXN')),
    published_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT jobs_published_integrity_check
        CHECK (status <> 'published' OR published_at IS NOT NULL),

    -- STORED generated column maintained by Postgres. App code MUST NOT
    -- maintain search_vector — see design decision #9.
    search_vector    tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('spanish', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('spanish', coalesce(description, '')), 'B')
    ) STORED
);

-- Full-text search via GIN on the generated column.
CREATE INDEX jobs_search_idx
    ON jobs USING GIN (search_vector);

-- B-tree for FK joins and per-company queries.
CREATE INDEX jobs_company_id_idx
    ON jobs (company_id);

-- Partial index backing keyset pagination on the public listing
-- (status='published' AND deleted_at IS NULL).
CREATE INDEX jobs_public_listing_idx
    ON jobs (published_at DESC)
    WHERE status = 'published' AND deleted_at IS NULL;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS jobs;
-- +goose StatementEnd