-- +goose Up
-- +goose StatementBegin
-- company_members (§spec/company-membership): the membership row that ties a
-- user to a company and assigns them a role. The one-company-per-user rule
-- and the closed role vocabulary are enforced HERE, at the DB boundary, so
-- future write paths cannot bypass them even if the domain layer has a bug.
--
-- Columns
--   id          UUID PK          -- v7 generated by the application.
--   user_id     UUID FK → users  -- one company per user; UNIQUE.
--   company_id  UUID FK → companies -- the company this user belongs to.
--   role        TEXT             -- 'owner' | 'recruiter'; closed set, see CHECK.
--   created_at  TIMESTAMPTZ      -- never NULL; default now().
--   updated_at  TIMESTAMPTZ      -- touched by UpdateRole; default now().
--
-- Integrity guard
--   * `role` is bounded by the NAMED CHECK `company_members_role_check` so a
--     buggy INSERT with role='admin' fails with SQLSTATE 23514, not a silent
--     string. The application also parses role via the `MemberRole` VO, but
--     the DB check is the last line of defence (design D7).
--   * `user_id` is UNIQUE — there is exactly ONE membership row per user.
--     Removal is HARD DELETE (design D2), so no partial index is needed;
--     re-inserting the same user_id after a remove is intentional.
CREATE TABLE company_members (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users (id),
    company_id  UUID NOT NULL REFERENCES companies (id),
    role        TEXT NOT NULL
        CONSTRAINT company_members_role_check
        CHECK (role IN ('owner', 'recruiter')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One company per user. UNIQUE not partial — see design D2 (hard delete).
CREATE UNIQUE INDEX company_members_user_id_unique
    ON company_members (user_id);

-- B-tree for FK joins and ListByCompanyID queries (`WHERE company_id = $1`).
CREATE INDEX company_members_company_id_idx
    ON company_members (company_id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE company_members;
-- +goose StatementEnd