-- +goose Up
-- +goose StatementBegin
-- audit_events (§spec/audit_events): the append-only audit log. Mirrors
-- docs/modelo-de-datos-proyecto-04.md §3.9 verbatim (design D1). The audit
-- INSERT (queries/audit_events.sql) runs inside the emitting write path's
-- pgx.Tx — both commit or both roll back (fail-closed co-write contract).
--
-- Columns
--   id           UUID PK           -- v7 generated by the emitting write path (no DB default).
--   occurred_at  TIMESTAMPTZ       -- server time; the INSERT omits it so DEFAULT now() (transaction time) applies.
--   actor_id     UUID NULL         -- NO FK by design: the audit log survives its actors. NULL ⇔ 'system'.
--   actor_type   TEXT              -- 'user' | 'system'. Closed vocabulary enforced by audit_events_actor_type_check.
--   event_type   TEXT              -- NO CHECK (§1.3 exception): event types grow constantly; adding one is a code change, never a migration.
--   entity_type  TEXT              -- free text; this slice only writes 'application'.
--   entity_id    UUID              -- NO FK (same survival rationale as actor_id).
--   metadata     JSONB             -- never NULL; DEFAULT '{}'. PII-free by construction (metadata builders pin the exact key set).
--
-- Integrity guards
--   * `actor_type` is bounded by the NAMED CHECK `audit_events_actor_type_check`
--     so a buggy INSERT with actor_type='robot' fails with SQLSTATE 23514.
--   * `event_type` deliberately carries NO CHECK — the §1.3 exception (event
--     types grow constantly; no migration per new type).
--   * No `updated_at`, no `deleted_at` — append-only, structurally.
--   * No FKs at all: the audit log must survive its actors and entities.
CREATE TABLE audit_events (
    id           UUID PRIMARY KEY,
    occurred_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor_id     UUID,
    actor_type   TEXT NOT NULL
        CONSTRAINT audit_events_actor_type_check
        CHECK (actor_type IN ('user', 'system')),
    event_type   TEXT NOT NULL,
    entity_type  TEXT NOT NULL,
    entity_id    UUID NOT NULL,
    metadata     JSONB NOT NULL DEFAULT '{}'
);

-- B-tree serving the future read surface (WHERE entity_type = $1 AND
-- entity_id = $2 ORDER BY occurred_at DESC). Not consumed this slice —
-- append-only means the read side is intentionally not delivered yet.
CREATE INDEX audit_events_entity_idx
    ON audit_events (entity_type, entity_id, occurred_at DESC);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Clean drop: the index drops with the table, and nothing references
-- `audit_events` (no FK dependents, no FK of its own).
DROP TABLE audit_events;
-- +goose StatementEnd
