-- +goose Up
-- +goose StatementBegin
-- applications (§spec/applications): the candidate-apply + recruiter-pipeline
-- bounded context. Mirrors docs/modelo-de-datos-proyecto-04.md §3.8 verbatim
-- (design D11). The atomic eligibility gate is in the SQL — `INSERT ... WHERE
-- EXISTS (jobs published AND deleted_at IS NULL AND companies active)` lives
-- in queries/applications.sql; the DDL here only establishes the schema
-- envelope.
--
-- Columns
--   id            UUID PK            -- v7 generated by the application (no DB default).
--   job_id        UUID FK → jobs     -- the target job.
--   candidate_id  UUID FK → users    -- the applying candidate (JWT sub → users.id).
--   status        TEXT               -- 'submitted' (DB default) | 'in_review' | 'rejected' | 'hired'.
--                                      Closed vocabulary enforced by applications_status_check.
--   source        TEXT NULL          -- 'referral' | 'linkedin' | 'job_board' | 'direct' | 'other'.
--                                      Closed vocabulary enforced by applications_source_check.
--                                      NULL when the candidate did not provide one.
--   cover_letter  TEXT NULL          -- free-text up to 2000 runes (validated in the use case, NOT here).
--   cv_s3_key     TEXT NULL          -- RESERVED — never set in this slice (LFPDPPP snapshot invariant).
--   anonymized_at TIMESTAMPTZ NULL   -- RESERVED — never set in this slice (LFPDPPP cancel flow).
--   created_at    TIMESTAMPTZ        -- never NULL; default now().
--   updated_at    TIMESTAMPTZ        -- touched on every transition; default now().
--
-- Integrity guards
--   * `status` is bounded by the NAMED CHECK `applications_status_check` so a
--     buggy INSERT with status='withdrawn' fails with SQLSTATE 23514, not a
--     silent string. The application also parses status via the
--     `ApplicationStatus` VO, but the DB check is the last line of defence.
--   * `source` is bounded by the NAMED CHECK `applications_source_check` so a
--     buggy INSERT with source='newspaper' fails with SQLSTATE 23514.
--   * `UNIQUE (job_id, candidate_id)` is the no-double-apply invariant. It is
--     PLAIN (not partial) because `applications` does not soft-delete in this
--     slice and there is no re-apply path (locked decision).
--   * FKs to jobs.id and users.id are NOT NULL — a missing target surfaces as
--     SQLSTATE 23503 (mapped to ErrInvalidApplicationReference at 400 in the
--     adapter; defense-in-depth, unreachable via the designed flow because the
--     atomic gate in CreateApplication filters to existing visible jobs).
CREATE TABLE applications (
    id            UUID PRIMARY KEY,
    job_id        UUID NOT NULL REFERENCES jobs (id),
    candidate_id  UUID NOT NULL REFERENCES users (id),
    status        TEXT NOT NULL DEFAULT 'submitted'
        CONSTRAINT applications_status_check
        CHECK (status IN ('submitted', 'in_review', 'rejected', 'hired')),
    source        TEXT
        CONSTRAINT applications_source_check
        CHECK (source IN ('referral', 'linkedin', 'job_board', 'direct', 'other')),
    cover_letter  TEXT,
    cv_s3_key     TEXT,
    anonymized_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT applications_job_candidate_unique UNIQUE (job_id, candidate_id)
);

-- B-tree backing the recruiter queue reads (WHERE job_id = $1 AND status = ...)
-- and the /me/applications list (WHERE candidate_id = $1, ORDER BY created_at DESC).
CREATE INDEX applications_by_job_idx
    ON applications (job_id, status, created_at DESC);
CREATE INDEX applications_by_candidate_idx
    ON applications (candidate_id, created_at DESC);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Clean drop: indexes and the implicit unique index drop with the table.
-- No other table in this slice references `applications`.
DROP TABLE applications;
-- +goose StatementEnd
