// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (id, job_id, candidate_id, source, cover_letter)
SELECT
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::text,
    $5::text
WHERE EXISTS (
    SELECT 1
    FROM jobs j
    JOIN companies c ON c.id = j.company_id
    WHERE j.id = $2::uuid
      AND j.status = 'published'
      AND j.deleted_at IS NULL
      AND c.status = 'active'
)
RETURNING id, job_id, candidate_id, status, source, cover_letter, created_at, updated_at
`

type CreateApplicationParams struct {
	ID          uuid.UUID   `json:"id"`
	JobID       uuid.UUID   `json:"job_id"`
	CandidateID uuid.UUID   `json:"candidate_id"`
	Source      pgtype.Text `json:"source"`
	CoverLetter pgtype.Text `json:"cover_letter"`
}

type CreateApplicationRow struct {
	ID          uuid.UUID          `json:"id"`
	JobID       uuid.UUID          `json:"job_id"`
	CandidateID uuid.UUID          `json:"candidate_id"`
	Status      string             `json:"status"`
	Source      pgtype.Text        `json:"source"`
	CoverLetter pgtype.Text        `json:"cover_letter"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Atomic apply + eligibility gate for POST /jobs/{jobId}/applications
// (design D1).
//
// The visibility predicate lives entirely in SQL (no Go-level read
// between middleware and INSERT). A zero-row outcome (draft / closed /
// soft-deleted job, suspended / pending_verification / missing company,
// or non-existent job) surfaces as pgx.ErrNoRows and the adapter maps
// it to ErrJobNotApplicable (404 "job not applicable" — single body
// shape, no leak).
//
// status is NOT inserted: the DB DEFAULT 'submitted' applies, so the
// row is born in the closed vocabulary's start state and no client write
// path can set a different value on create.
//
// cv_s3_key and anonymized_at are NOT in the INSERT column list and
// NOT in the RETURNING list — the reserved columns stay NULL and never
// reach the wire (D11).
//
// source / cover_letter are sqlc.narg (nullable): absent on the wire →
// SQL NULL.
func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (CreateApplicationRow, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.JobID,
		arg.CandidateID,
		arg.Source,
		arg.CoverLetter,
	)
	var i CreateApplicationRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CandidateID,
		&i.Status,
		&i.Source,
		&i.CoverLetter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT
    a.id, a.job_id, a.candidate_id, a.status, a.source, a.cover_letter,
    a.created_at, a.updated_at,
    u.full_name AS candidate_full_name,
    cp.professional_title AS candidate_professional_title,
    cp.years_of_experience AS candidate_years_of_experience
FROM applications a
JOIN jobs j ON j.id = a.job_id
JOIN users u ON u.id = a.candidate_id
LEFT JOIN candidate_profiles cp ON cp.user_id = a.candidate_id
WHERE a.id         = $1::uuid
  AND a.job_id     = $2::uuid
  AND j.company_id = $3::uuid
`

type GetApplicationByIDParams struct {
	ID        uuid.UUID `json:"id"`
	JobID     uuid.UUID `json:"job_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

type GetApplicationByIDRow struct {
	ID                         uuid.UUID          `json:"id"`
	JobID                      uuid.UUID          `json:"job_id"`
	CandidateID                uuid.UUID          `json:"candidate_id"`
	Status                     string             `json:"status"`
	Source                     pgtype.Text        `json:"source"`
	CoverLetter                pgtype.Text        `json:"cover_letter"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	CandidateFullName          string             `json:"candidate_full_name"`
	CandidateProfessionalTitle pgtype.Text        `json:"candidate_professional_title"`
	CandidateYearsOfExperience pgtype.Int2        `json:"candidate_years_of_experience"`
}

// Recruiter detail endpoint (design D5 / spec scenario "recruiter gets
// an application's detail"). Scopes by (id, job_id, company_id) and
// joins users (full_name) + candidate_profiles (LEFT JOIN — professional
// title + years_of_experience ONLY for PII minimization, D12).
//
// 0 rows → pgx.ErrNoRows → entities.ErrApplicationNotFound (404).
func (q *Queries) GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (GetApplicationByIDRow, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, arg.ID, arg.JobID, arg.CompanyID)
	var i GetApplicationByIDRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CandidateID,
		&i.Status,
		&i.Source,
		&i.CoverLetter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CandidateFullName,
		&i.CandidateProfessionalTitle,
		&i.CandidateYearsOfExperience,
	)
	return i, err
}

const getJobForApplicationsScope = `-- name: GetJobForApplicationsScope :one
SELECT id
FROM jobs
WHERE id         = $1::uuid
  AND company_id = $2::uuid
`

type GetJobForApplicationsScopeParams struct {
	JobID     uuid.UUID `json:"job_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Same-company scope check for the recruiter list (design D5). Reads
// jobs directly (cross-feature SQL in the applications adapter; the
// jobs port is NOT extended). No deleted_at / status filter: soft-
// deleted jobs remain recruiter-accessible.
//
// 0 rows → pgx.ErrNoRows → ErrApplicationNotFound (cross-company /
// non-existent).
func (q *Queries) GetJobForApplicationsScope(ctx context.Context, arg GetJobForApplicationsScopeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getJobForApplicationsScope, arg.JobID, arg.CompanyID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listApplicationsByJob = `-- name: ListApplicationsByJob :many
SELECT
    a.id, a.job_id, a.candidate_id, a.status, a.source, a.cover_letter,
    a.created_at, a.updated_at,
    u.full_name AS candidate_full_name,
    cp.professional_title AS candidate_professional_title,
    cp.years_of_experience AS candidate_years_of_experience
FROM applications a
JOIN jobs j ON j.id = a.job_id
JOIN users u ON u.id = a.candidate_id
LEFT JOIN candidate_profiles cp ON cp.user_id = a.candidate_id
WHERE a.job_id     = $1::uuid
  AND j.company_id = $2::uuid
ORDER BY a.created_at DESC, a.id DESC
LIMIT 100
`

type ListApplicationsByJobParams struct {
	JobID     uuid.UUID `json:"job_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

type ListApplicationsByJobRow struct {
	ID                         uuid.UUID          `json:"id"`
	JobID                      uuid.UUID          `json:"job_id"`
	CandidateID                uuid.UUID          `json:"candidate_id"`
	Status                     string             `json:"status"`
	Source                     pgtype.Text        `json:"source"`
	CoverLetter                pgtype.Text        `json:"cover_letter"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	CandidateFullName          string             `json:"candidate_full_name"`
	CandidateProfessionalTitle pgtype.Text        `json:"candidate_professional_title"`
	CandidateYearsOfExperience pgtype.Int2        `json:"candidate_years_of_experience"`
}

// Recruiter queue read (design D5 second step). Same-company scope
// enforced inside the same statement. NO deleted_at / status filter on
// jobs: soft-deleted jobs' applications remain recruiter-accessible
// (locked decision).
//
// Hard cap 100 (no pagination in this slice).
func (q *Queries) ListApplicationsByJob(ctx context.Context, arg ListApplicationsByJobParams) ([]ListApplicationsByJobRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByJob, arg.JobID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsByJobRow
	for rows.Next() {
		var i ListApplicationsByJobRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.CandidateID,
			&i.Status,
			&i.Source,
			&i.CoverLetter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CandidateFullName,
			&i.CandidateProfessionalTitle,
			&i.CandidateYearsOfExperience,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyApplications = `-- name: ListMyApplications :many
SELECT
    a.id, a.job_id, a.candidate_id, a.status, a.source, a.cover_letter,
    a.created_at, a.updated_at,
    j.title AS job_title,
    c.id   AS company_id,
    c.name AS company_name
FROM applications a
JOIN jobs j ON j.id = a.job_id
JOIN companies c ON c.id = j.company_id
WHERE a.candidate_id = $1::uuid
ORDER BY a.created_at DESC, a.id DESC
LIMIT 100
`

type ListMyApplicationsRow struct {
	ID          uuid.UUID          `json:"id"`
	JobID       uuid.UUID          `json:"job_id"`
	CandidateID uuid.UUID          `json:"candidate_id"`
	Status      string             `json:"status"`
	Source      pgtype.Text        `json:"source"`
	CoverLetter pgtype.Text        `json:"cover_letter"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	JobTitle    string             `json:"job_title"`
	CompanyID   uuid.UUID          `json:"company_id"`
	CompanyName string             `json:"company_name"`
}

// Candidate's GET /me/applications list. Joins jobs (title) + companies
// (id, name) to render the embedded job summary. NOT redacted by
// jobs.deleted_at on purpose: the candidate's own history persists
// even if the job has since been soft-deleted (locked decision).
//
// Hard cap 100 (no pagination in this slice).
func (q *Queries) ListMyApplications(ctx context.Context, candidateID uuid.UUID) ([]ListMyApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listMyApplications, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyApplicationsRow
	for rows.Next() {
		var i ListMyApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.CandidateID,
			&i.Status,
			&i.Source,
			&i.CoverLetter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
			&i.CompanyID,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionStatus = `-- name: TransitionStatus :one
UPDATE applications a
SET status     = $1::text,
    updated_at = now()
WHERE a.id        = $2::uuid
  AND a.job_id    = $3::uuid
  AND a.status    = $4::text
  AND EXISTS (
      SELECT 1
      FROM jobs j
      WHERE j.id = a.job_id
        AND j.company_id = $5::uuid
  )
RETURNING id, job_id, candidate_id, status, source, cover_letter, created_at, updated_at
`

type TransitionStatusParams struct {
	ToStatus   string    `json:"to_status"`
	ID         uuid.UUID `json:"id"`
	JobID      uuid.UUID `json:"job_id"`
	FromStatus string    `json:"from_status"`
	CompanyID  uuid.UUID `json:"company_id"`
}

type TransitionStatusRow struct {
	ID          uuid.UUID          `json:"id"`
	JobID       uuid.UUID          `json:"job_id"`
	CandidateID uuid.UUID          `json:"candidate_id"`
	Status      string             `json:"status"`
	Source      pgtype.Text        `json:"source"`
	CoverLetter pgtype.Text        `json:"cover_letter"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Recruiter transition with the same-company invariant + the lost-race
// status guard (no CAS — design D3). The WHERE narrows to (id, job_id,
// status = expected_from) and scopes the owning job to the caller's
// company via EXISTS. 0 rows → pgx.ErrNoRows → ErrApplicationNotFound
// (lost race / cross-company / non-existent / mismatched job —
// indistinguishable, 404).
//
// No deleted_at / status filter on jobs: transitions on soft-deleted
// jobs' applications remain legal (historical pipeline).
func (q *Queries) TransitionStatus(ctx context.Context, arg TransitionStatusParams) (TransitionStatusRow, error) {
	row := q.db.QueryRow(ctx, transitionStatus,
		arg.ToStatus,
		arg.ID,
		arg.JobID,
		arg.FromStatus,
		arg.CompanyID,
	)
	var i TransitionStatusRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CandidateID,
		&i.Status,
		&i.Source,
		&i.CoverLetter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
