// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (id, actor_id, actor_type, event_type, entity_type, entity_id, metadata)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text,
    $5::text,
    $6::uuid,
    $7::jsonb
)
`

type InsertAuditEventParams struct {
	ID         uuid.UUID   `json:"id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	ActorType  string      `json:"actor_type"`
	EventType  string      `json:"event_type"`
	EntityType string      `json:"entity_type"`
	EntityID   uuid.UUID   `json:"entity_id"`
	Metadata   []byte      `json:"metadata"`
}

// Append-only INSERT (the audit_events slice has NO read / update / delete
// surface). occurred_at is deliberately OMITTED so the DB DEFAULT now()
// (transaction time) applies; the emitting write path does not supply a
// client clock. id is the uuid.NewV7 generated by the emitting write path.
// actor_id is sqlc.narg (nullable): 'user' events carry the actor's
// users.id; 'system' events (not emitted this slice) carry SQL NULL.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.ActorID,
		arg.ActorType,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}
