// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidates.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCandidateLanguagesByUserID = `-- name: DeleteCandidateLanguagesByUserID :exec
DELETE FROM candidate_languages
WHERE user_id = $1
`

func (q *Queries) DeleteCandidateLanguagesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCandidateLanguagesByUserID, userID)
	return err
}

const getCandidateProfileByUserID = `-- name: GetCandidateProfileByUserID :one
SELECT user_id, phone, linkedin_url, portfolio_url, professional_title, current_company, years_of_experience, profile_summary, birth_date, city, country, education_level, field_of_study, skills, current_salary_gross, current_salary_net, expected_salary, salary_currency, expected_salary_period, cv_s3_key, created_at, updated_at, search_vector FROM candidate_profiles
WHERE user_id = $1
`

func (q *Queries) GetCandidateProfileByUserID(ctx context.Context, userID uuid.UUID) (CandidateProfile, error) {
	row := q.db.QueryRow(ctx, getCandidateProfileByUserID, userID)
	var i CandidateProfile
	err := row.Scan(
		&i.UserID,
		&i.Phone,
		&i.LinkedinUrl,
		&i.PortfolioUrl,
		&i.ProfessionalTitle,
		&i.CurrentCompany,
		&i.YearsOfExperience,
		&i.ProfileSummary,
		&i.BirthDate,
		&i.City,
		&i.Country,
		&i.EducationLevel,
		&i.FieldOfStudy,
		&i.Skills,
		&i.CurrentSalaryGross,
		&i.CurrentSalaryNet,
		&i.ExpectedSalary,
		&i.SalaryCurrency,
		&i.ExpectedSalaryPeriod,
		&i.CvS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const insertCandidateLanguage = `-- name: InsertCandidateLanguage :exec
INSERT INTO candidate_languages (user_id, language, level)
VALUES ($1, $2, $3)
`

type InsertCandidateLanguageParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Language string    `json:"language"`
	Level    string    `json:"level"`
}

// Used inside the atomic replace transaction. Composite PK (user_id, language)
// prevents duplicate languages for the same user — the adapter surfaces a
// 23505 as ErrDuplicateLanguage.
func (q *Queries) InsertCandidateLanguage(ctx context.Context, arg InsertCandidateLanguageParams) error {
	_, err := q.db.Exec(ctx, insertCandidateLanguage, arg.UserID, arg.Language, arg.Level)
	return err
}

const listCandidateLanguagesByUserID = `-- name: ListCandidateLanguagesByUserID :many
SELECT user_id, language, level FROM candidate_languages
WHERE user_id = $1
ORDER BY language
`

func (q *Queries) ListCandidateLanguagesByUserID(ctx context.Context, userID uuid.UUID) ([]CandidateLanguage, error) {
	rows, err := q.db.Query(ctx, listCandidateLanguagesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateLanguage
	for rows.Next() {
		var i CandidateLanguage
		if err := rows.Scan(&i.UserID, &i.Language, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCandidateProfile = `-- name: UpsertCandidateProfile :one
INSERT INTO candidate_profiles (
    user_id, phone, linkedin_url, portfolio_url, professional_title,
    current_company, years_of_experience, profile_summary, birth_date,
    city, country, education_level, field_of_study, skills,
    current_salary_gross, current_salary_net, expected_salary,
    salary_currency, expected_salary_period, cv_s3_key,
    created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16, $17,
    $18, $19, $20,
    now(), now()
)
ON CONFLICT (user_id) DO UPDATE SET
    phone                  = EXCLUDED.phone,
    linkedin_url           = EXCLUDED.linkedin_url,
    portfolio_url          = EXCLUDED.portfolio_url,
    professional_title     = EXCLUDED.professional_title,
    current_company        = EXCLUDED.current_company,
    years_of_experience    = EXCLUDED.years_of_experience,
    profile_summary        = EXCLUDED.profile_summary,
    birth_date             = EXCLUDED.birth_date,
    city                   = EXCLUDED.city,
    country                = EXCLUDED.country,
    education_level        = EXCLUDED.education_level,
    field_of_study         = EXCLUDED.field_of_study,
    skills                 = EXCLUDED.skills,
    current_salary_gross   = EXCLUDED.current_salary_gross,
    current_salary_net     = EXCLUDED.current_salary_net,
    expected_salary        = EXCLUDED.expected_salary,
    salary_currency        = EXCLUDED.salary_currency,
    expected_salary_period = EXCLUDED.expected_salary_period,
    cv_s3_key              = EXCLUDED.cv_s3_key,
    updated_at             = now()
RETURNING user_id, phone, linkedin_url, portfolio_url, professional_title, current_company, years_of_experience, profile_summary, birth_date, city, country, education_level, field_of_study, skills, current_salary_gross, current_salary_net, expected_salary, salary_currency, expected_salary_period, cv_s3_key, created_at, updated_at, search_vector
`

type UpsertCandidateProfileParams struct {
	UserID               uuid.UUID   `json:"user_id"`
	Phone                pgtype.Text `json:"phone"`
	LinkedinUrl          pgtype.Text `json:"linkedin_url"`
	PortfolioUrl         pgtype.Text `json:"portfolio_url"`
	ProfessionalTitle    pgtype.Text `json:"professional_title"`
	CurrentCompany       pgtype.Text `json:"current_company"`
	YearsOfExperience    pgtype.Int2 `json:"years_of_experience"`
	ProfileSummary       pgtype.Text `json:"profile_summary"`
	BirthDate            pgtype.Date `json:"birth_date"`
	City                 pgtype.Text `json:"city"`
	Country              pgtype.Text `json:"country"`
	EducationLevel       pgtype.Text `json:"education_level"`
	FieldOfStudy         pgtype.Text `json:"field_of_study"`
	Skills               []string    `json:"skills"`
	CurrentSalaryGross   pgtype.Int4 `json:"current_salary_gross"`
	CurrentSalaryNet     pgtype.Int4 `json:"current_salary_net"`
	ExpectedSalary       pgtype.Int4 `json:"expected_salary"`
	SalaryCurrency       string      `json:"salary_currency"`
	ExpectedSalaryPeriod pgtype.Text `json:"expected_salary_period"`
	CvS3Key              pgtype.Text `json:"cv_s3_key"`
}

// Idempotent upsert keyed on the PK (user_id). First PUT creates the row;
// subsequent PUTs overwrite the editable columns. search_vector is a STORED
// generated column owned by Postgres and MUST NOT be touched here.
func (q *Queries) UpsertCandidateProfile(ctx context.Context, arg UpsertCandidateProfileParams) (CandidateProfile, error) {
	row := q.db.QueryRow(ctx, upsertCandidateProfile,
		arg.UserID,
		arg.Phone,
		arg.LinkedinUrl,
		arg.PortfolioUrl,
		arg.ProfessionalTitle,
		arg.CurrentCompany,
		arg.YearsOfExperience,
		arg.ProfileSummary,
		arg.BirthDate,
		arg.City,
		arg.Country,
		arg.EducationLevel,
		arg.FieldOfStudy,
		arg.Skills,
		arg.CurrentSalaryGross,
		arg.CurrentSalaryNet,
		arg.ExpectedSalary,
		arg.SalaryCurrency,
		arg.ExpectedSalaryPeriod,
		arg.CvS3Key,
	)
	var i CandidateProfile
	err := row.Scan(
		&i.UserID,
		&i.Phone,
		&i.LinkedinUrl,
		&i.PortfolioUrl,
		&i.ProfessionalTitle,
		&i.CurrentCompany,
		&i.YearsOfExperience,
		&i.ProfileSummary,
		&i.BirthDate,
		&i.City,
		&i.Country,
		&i.EducationLevel,
		&i.FieldOfStudy,
		&i.Skills,
		&i.CurrentSalaryGross,
		&i.CurrentSalaryNet,
		&i.ExpectedSalary,
		&i.SalaryCurrency,
		&i.ExpectedSalaryPeriod,
		&i.CvS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}
