// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCompanyMember = `-- name: CreateCompanyMember :one
INSERT INTO company_members (id, user_id, company_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, company_id, role, created_at, updated_at
`

type CreateCompanyMemberParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CompanyID uuid.UUID `json:"company_id"`
	Role      string    `json:"role"`
}

// Adds a row to `company_members`. UNIQUE(user_id) means a second insert with
// the same user_id surfaces SQLSTATE 23505 to the adapter (mapped to
// ErrMemberExists in the companies/infrastructure layer); FK violations on
// user_id / company_id surface SQLSTATE 23503 (mapped to ErrUserNotFound /
// ErrCompanyNotFound).
func (q *Queries) CreateCompanyMember(ctx context.Context, arg CreateCompanyMemberParams) (CompanyMember, error) {
	row := q.db.QueryRow(ctx, createCompanyMember,
		arg.ID,
		arg.UserID,
		arg.CompanyID,
		arg.Role,
	)
	var i CompanyMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipByUserID = `-- name: GetMembershipByUserID :one
SELECT id, user_id, company_id, role, created_at, updated_at
FROM company_members
WHERE user_id = $1
`

// Single membership lookup for the membership-resolver chain
// (`sub → users.id → company_members`) — see design D6. Returns
// pgx.ErrNoRows when the user has no membership, which the service maps to
// ErrNotAMember.
func (q *Queries) GetMembershipByUserID(ctx context.Context, userID uuid.UUID) (CompanyMember, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserID, userID)
	var i CompanyMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listByCompanyID = `-- name: ListByCompanyID :many
SELECT id, user_id, company_id, role, created_at, updated_at
FROM company_members
WHERE company_id = $1
ORDER BY created_at ASC, id ASC
`

// All members of a company (GET /me/company/members). Ordered by created_at
// for stable rendering; backed by the `company_members_company_id_idx` B-tree.
func (q *Queries) ListByCompanyID(ctx context.Context, companyID uuid.UUID) ([]CompanyMember, error) {
	rows, err := q.db.Query(ctx, listByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyMember
	for rows.Next() {
		var i CompanyMember
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCompanyMember = `-- name: RemoveCompanyMember :exec
DELETE FROM company_members
WHERE id = $1 AND company_id = $2
`

type RemoveCompanyMemberParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Same-company guard (design D7) — see UpdateMemberRole for rationale.
// HARD DELETE (design D2) frees `user_id` for re-assignment.
func (q *Queries) RemoveCompanyMember(ctx context.Context, arg RemoveCompanyMemberParams) error {
	_, err := q.db.Exec(ctx, removeCompanyMember, arg.ID, arg.CompanyID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE company_members
SET role = $3, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateMemberRoleParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Role      string    `json:"role"`
}

// Same-company guard (design D7): the SQL predicate
// `id = $1 AND company_id = $2` is the race-free, IDOR-proof boundary for
// UpdateRole. 0 rows affected → ErrMemberNotFound in the adapter.
// `updated_at` is touched here so downstream callers never have to remember
// to do it.
func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.ID, arg.CompanyID, arg.Role)
	return err
}
