// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
    id, name, rfc, industry_id, website, logo_url,
    description, size, founded_year, city, country,
    linkedin_url, instagram_url, facebook_url, twitter_url, cover_image_url
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16
)
RETURNING id, name, rfc, industry_id, website, logo_url, status, created_at, updated_at, deleted_at, description, size, founded_year, city, country, linkedin_url, instagram_url, facebook_url, twitter_url, cover_image_url
`

type CreateCompanyParams struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Rfc           string      `json:"rfc"`
	IndustryID    string      `json:"industry_id"`
	Website       pgtype.Text `json:"website"`
	LogoUrl       pgtype.Text `json:"logo_url"`
	Description   pgtype.Text `json:"description"`
	Size          pgtype.Text `json:"size"`
	FoundedYear   pgtype.Int2 `json:"founded_year"`
	City          pgtype.Text `json:"city"`
	Country       pgtype.Text `json:"country"`
	LinkedinUrl   pgtype.Text `json:"linkedin_url"`
	InstagramUrl  pgtype.Text `json:"instagram_url"`
	FacebookUrl   pgtype.Text `json:"facebook_url"`
	TwitterUrl    pgtype.Text `json:"twitter_url"`
	CoverImageUrl pgtype.Text `json:"cover_image_url"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.Name,
		arg.Rfc,
		arg.IndustryID,
		arg.Website,
		arg.LogoUrl,
		arg.Description,
		arg.Size,
		arg.FoundedYear,
		arg.City,
		arg.Country,
		arg.LinkedinUrl,
		arg.InstagramUrl,
		arg.FacebookUrl,
		arg.TwitterUrl,
		arg.CoverImageUrl,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rfc,
		&i.IndustryID,
		&i.Website,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Description,
		&i.Size,
		&i.FoundedYear,
		&i.City,
		&i.Country,
		&i.LinkedinUrl,
		&i.InstagramUrl,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.CoverImageUrl,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, rfc, industry_id, website, logo_url, status, created_at, updated_at, deleted_at, description, size, founded_year, city, country, linkedin_url, instagram_url, facebook_url, twitter_url, cover_image_url FROM companies
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rfc,
		&i.IndustryID,
		&i.Website,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Description,
		&i.Size,
		&i.FoundedYear,
		&i.City,
		&i.Country,
		&i.LinkedinUrl,
		&i.InstagramUrl,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.CoverImageUrl,
	)
	return i, err
}

const isCompanyLive = `-- name: IsCompanyLive :one
SELECT ((deleted_at IS NULL)::boolean) AS is_live
FROM companies
WHERE id = $1
`

// Atomic liveness probe for the RequireCompanyRole middleware
// (require-company-role-tombstone-gate slice). Returns `deleted_at IS NULL`
// for the exact company id WITHOUT filtering away tombstones:
//
//   - Row present, deleted_at IS NULL    → true  (live company)
//   - Row present, deleted_at IS NOT NULL → false (tombstoned company)
//   - Row absent (no such id)           → pgx.ErrNoRows → adapter maps
//     to entities.ErrCompanyNotFound
//     (the middleware collapses
//     ErrCompanyNotFound + false to
//     the same 403 — the gate cannot
//     reveal which one it saw)
//
// The probe is ONE column (boolean) so it is cheaper than GetCompanyByID
// (which SELECTs 22 columns and rebuilds the entity). The `id = $1`
// predicate carries NO `deleted_at IS NULL` filter — the gate must see
// the tombstone, not skip past it.
//
// `:one` (not `:exec`) is chosen deliberately: the middleware needs
// the boolean to dispatch, and `:one` matches the per-row scalar
// semantics used by every other read in this file. A missing row
// surfaces as pgx.ErrNoRows at the adapter boundary.
func (q *Queries) IsCompanyLive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isCompanyLive, id)
	var is_live bool
	err := row.Scan(&is_live)
	return is_live, err
}

const softDeleteCompany = `-- name: SoftDeleteCompany :one
WITH upd AS (
    UPDATE companies
    SET
        deleted_at = now(),
        updated_at = clock_timestamp()
    WHERE id         = $1::uuid
      AND deleted_at IS NULL
      AND updated_at = $2::timestamptz
    RETURNING id
)
SELECT (SELECT count(*) FROM upd) AS deleted_count
`

type SoftDeleteCompanyParams struct {
	CompanyID uuid.UUID          `json:"company_id"`
	CasToken  pgtype.Timestamptz `json:"cas_token"`
}

// Atomic soft-delete + CAS for DELETE /me/company (companies-write
// slice, design D4). Minimal SET list: ONLY deleted_at = now() and
// updated_at = clock_timestamp(). rfc / industry_id / status /
// created_at / id and the 12 profile columns are PRESERVED as audit
// history (a future restore endpoint operates on the intact row).
//
// No `active` CTE (locked §6.10: no active-company guard on PATCH/DELETE
// — a suspended company may be tombstoned). The WHERE scopes by id +
// `deleted_at IS NULL` + CAS `updated_at`.
//
// Outcome matrix (adapter D4 + D11):
//
//	deleted_count = 0  → ErrCompanyNotFound (CAS lost / already
//	                       soft-deleted / cross-company / non-existent —
//	                       indistinguishable by design)
//	deleted_count = 1  → nil (success: 1 row tombstoned)
//
// The final scalar SELECT (no FROM, no WHERE) ALWAYS returns exactly
// one row, so pgx.ErrNoRows is unreachable via the designed flow;
// mapSoftDeleteCompanyError keeps it as defense-in-depth.
//
// `closed_count` / 23514 dispatch — `companies` has no CHECK
// constraints the minimal SET list can trip (the `name` length /
// `description` length are VO-only; `companies_size_check` /
// `companies_founded_year_check` only fire on UPDATE with NEW values;
// `companies_status_check` is unreachable since `status` is never
// touched). `23514 → ErrInvalidCompanyStatusTransition` is kept as
// defense-in-depth.
func (q *Queries) SoftDeleteCompany(ctx context.Context, arg SoftDeleteCompanyParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteCompany, arg.CompanyID, arg.CasToken)
	var deleted_count int64
	err := row.Scan(&deleted_count)
	return deleted_count, err
}

const updateCompany = `-- name: UpdateCompany :one
WITH upd AS (
    UPDATE companies
    SET
        name            = COALESCE($1::text, name),
        website         = CASE WHEN $2::boolean
                                THEN $3::text ELSE website END,
        logo_url        = CASE WHEN $4::boolean
                                THEN $5::text ELSE logo_url END,
        description     = CASE WHEN $6::boolean
                                THEN $7::text ELSE description END,
        size            = CASE WHEN $8::boolean
                                THEN $9::text ELSE size END,
        founded_year    = CASE WHEN $10::boolean
                                THEN $11::int2 ELSE founded_year END,
        city            = CASE WHEN $12::boolean
                                THEN $13::text ELSE city END,
        country         = CASE WHEN $14::boolean
                                THEN $15::text ELSE country END,
        linkedin_url    = CASE WHEN $16::boolean
                                THEN $17::text ELSE linkedin_url END,
        instagram_url   = CASE WHEN $18::boolean
                                THEN $19::text ELSE instagram_url END,
        facebook_url    = CASE WHEN $20::boolean
                                THEN $21::text ELSE facebook_url END,
        twitter_url     = CASE WHEN $22::boolean
                                THEN $23::text ELSE twitter_url END,
        cover_image_url = CASE WHEN $24::boolean
                                THEN $25::text ELSE cover_image_url END,
        updated_at      = clock_timestamp()
    WHERE id         = $26::uuid
      AND deleted_at IS NULL
      AND updated_at = $27::timestamptz
    RETURNING id
)
SELECT (SELECT count(*) FROM upd) AS updated_count
`

type UpdateCompanyParams struct {
	Name             pgtype.Text        `json:"name"`
	SetWebsite       bool               `json:"set_website"`
	Website          pgtype.Text        `json:"website"`
	SetLogoUrl       bool               `json:"set_logo_url"`
	LogoUrl          pgtype.Text        `json:"logo_url"`
	SetDescription   bool               `json:"set_description"`
	Description      pgtype.Text        `json:"description"`
	SetSize          bool               `json:"set_size"`
	Size             pgtype.Text        `json:"size"`
	SetFoundedYear   bool               `json:"set_founded_year"`
	FoundedYear      pgtype.Int2        `json:"founded_year"`
	SetCity          bool               `json:"set_city"`
	City             pgtype.Text        `json:"city"`
	SetCountry       bool               `json:"set_country"`
	Country          pgtype.Text        `json:"country"`
	SetLinkedinUrl   bool               `json:"set_linkedin_url"`
	LinkedinUrl      pgtype.Text        `json:"linkedin_url"`
	SetInstagramUrl  bool               `json:"set_instagram_url"`
	InstagramUrl     pgtype.Text        `json:"instagram_url"`
	SetFacebookUrl   bool               `json:"set_facebook_url"`
	FacebookUrl      pgtype.Text        `json:"facebook_url"`
	SetTwitterUrl    bool               `json:"set_twitter_url"`
	TwitterUrl       pgtype.Text        `json:"twitter_url"`
	SetCoverImageUrl bool               `json:"set_cover_image_url"`
	CoverImageUrl    pgtype.Text        `json:"cover_image_url"`
	CompanyID        uuid.UUID          `json:"company_id"`
	CasToken         pgtype.Timestamptz `json:"cas_token"`
}

// Atomic partial update + CAS for PATCH /me/company (companies-write slice,
// design D3). Mirrors UpdateJob :one minus the `active` CTE (companies
// has no active-company guard on PATCH/DELETE — a suspended company may
// edit its profile; `status` is not patchable).
//
// Column-update shapes:
//   - name            via COALESCE(sqlc.narg('name')::text, name)  (non-nullable, no clear-to-NULL)
//   - 12 profile cols via CASE WHEN sqlc.arg('set_<field>')::boolean
//     THEN sqlc.narg('<field>')::...
//     ELSE col END                          (tri-state — design D7)
//   - updated_at      = clock_timestamp()                          (advances in the same statement)
//
// Tri-state decode per column (matches jobs design D7):
//
//	Set=false              -> CASE branch: ELSE col      (untouched)
//	Set=true, Valid=false  -> CASE branch: THEN narg     -> NULL    (clear)
//	Set=true, Valid=true   -> CASE branch: THEN narg     -> value
//
// CAS in the UPDATE WHERE: `updated_at = sqlc.arg('cas_token')` — atomic
// race-free guard for the row predicates (id, deleted_at IS NULL). Two
// writers holding the same CAS: only one UPDATE returns 1 row in `upd`;
// the other returns 0.
//
// The final SELECT is scalar (no FROM, no WHERE) and ALWAYS returns
// exactly one row. pgx.ErrNoRows is unreachable via the designed flow;
// mapUpdateCompanyError keeps it as defense-in-depth (mirrors jobs
// mapUpdateError).
//
// Never touched: rfc, industry_id, status, created_at, id, deleted_at.
func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Name,
		arg.SetWebsite,
		arg.Website,
		arg.SetLogoUrl,
		arg.LogoUrl,
		arg.SetDescription,
		arg.Description,
		arg.SetSize,
		arg.Size,
		arg.SetFoundedYear,
		arg.FoundedYear,
		arg.SetCity,
		arg.City,
		arg.SetCountry,
		arg.Country,
		arg.SetLinkedinUrl,
		arg.LinkedinUrl,
		arg.SetInstagramUrl,
		arg.InstagramUrl,
		arg.SetFacebookUrl,
		arg.FacebookUrl,
		arg.SetTwitterUrl,
		arg.TwitterUrl,
		arg.SetCoverImageUrl,
		arg.CoverImageUrl,
		arg.CompanyID,
		arg.CasToken,
	)
	var updated_count int64
	err := row.Scan(&updated_count)
	return updated_count, err
}
