// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

// Package db
package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (id, name, rfc, industry_id, website, logo_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, rfc, industry_id, website, logo_url, status, created_at, updated_at, deleted_at
`

type CreateCompanyParams struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Rfc        string      `json:"rfc"`
	IndustryID string      `json:"industry_id"`
	Website    pgtype.Text `json:"website"`
	LogoUrl    pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.Name,
		arg.Rfc,
		arg.IndustryID,
		arg.Website,
		arg.LogoUrl,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rfc,
		&i.IndustryID,
		&i.Website,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, rfc, industry_id, website, logo_url, status, created_at, updated_at, deleted_at FROM companies 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rfc,
		&i.IndustryID,
		&i.Website,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
