// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: industries.sql

package db

import (
	"context"
)

const listActiveIndustries = `-- name: ListActiveIndustries :many
SELECT id, label_es, label_en, sort_order, active, created_at, updated_at FROM industries
WHERE active = true
ORDER BY sort_order, id
`

func (q *Queries) ListActiveIndustries(ctx context.Context) ([]Industry, error) {
	rows, err := q.db.Query(ctx, listActiveIndustries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Industry
	for rows.Next() {
		var i Industry
		if err := rows.Scan(
			&i.ID,
			&i.LabelEs,
			&i.LabelEn,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
