// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
WITH active AS (
    SELECT id, name
    FROM companies
    WHERE id = $1::uuid
      AND status = 'active'
),
ins AS (
    INSERT INTO jobs (
        id, company_id, title, description, work_mode, employment_type,
        seniority, status, location, salary_min, salary_max, salary_currency
    )
    SELECT
        $2::uuid,
        active.id,
        $3::text,
        $4::text,
        $5::text,
        $6::text,
        $7::text,
        'draft',
        $8::text,
        $9::int,
        $10::int,
        $11::text
    FROM active
    RETURNING
        id, title, description, location, work_mode, employment_type,
        seniority, salary_min, salary_max, salary_currency, status,
        published_at, updated_at, company_id
)
SELECT
    ins.id,
    ins.title,
    ins.description,
    ins.location,
    ins.work_mode,
    ins.employment_type,
    ins.seniority,
    ins.salary_min,
    ins.salary_max,
    ins.salary_currency,
    ins.status,
    ins.published_at,
    ins.updated_at,
    ins.company_id,
    active.name AS company_name
FROM ins
JOIN active ON active.id = ins.company_id
`

type CreateJobParams struct {
	CompanyID      uuid.UUID   `json:"company_id"`
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	Description    string      `json:"description"`
	WorkMode       string      `json:"work_mode"`
	EmploymentType string      `json:"employment_type"`
	Seniority      string      `json:"seniority"`
	Location       pgtype.Text `json:"location"`
	SalaryMin      pgtype.Int4 `json:"salary_min"`
	SalaryMax      pgtype.Int4 `json:"salary_max"`
	SalaryCurrency string      `json:"salary_currency"`
}

type CreateJobRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Location       pgtype.Text        `json:"location"`
	WorkMode       string             `json:"work_mode"`
	EmploymentType string             `json:"employment_type"`
	Seniority      string             `json:"seniority"`
	SalaryMin      pgtype.Int4        `json:"salary_min"`
	SalaryMax      pgtype.Int4        `json:"salary_max"`
	SalaryCurrency string             `json:"salary_currency"`
	Status         string             `json:"status"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompanyID      uuid.UUID          `json:"company_id"`
	CompanyName    string             `json:"company_name"`
}

// Atomic create for POST /jobs (design D1/D2/D3).
//
// Two guarantees live in this single statement:
//  1. Active-company gate: the `active` CTE selects the owning company
//     ONLY when status='active'. A suspended / pending_verification /
//     missing company yields zero rows in `active`, so `ins` inserts
//     zero rows and the final SELECT returns zero rows -> the adapter
//     maps pgx.ErrNoRows -> entities.ErrCompanyNotActive (the
//     predicate and the write are the same statement -- no TOCTOU
//     window).
//  2. Single-round-trip editor view: the final SELECT joins `ins`
//     back to `active` to carry company_name, so the output column
//     set is EXACTLY the GetJobForUpdate column set and the adapter
//     reuses toJobForUpdateEntity via a thin row lift.
//
// status is written explicitly as 'draft' (locked decision #1): the
// row is born hidden from the public read path (status='published'
// predicate) and the explicit value is immune to a future DEFAULT drift.
//
// salary_currency is always supplied by the use case (nil -> MXN in Go),
// so it is a required arg, never NULL. location / salary_min /
// salary_max are nullable (sqlc.narg).
//
// search_vector (STORED generated) is EXCLUDED from BOTH the INSERT
// column list and every output list -- a `RETURNING *` would map
// tsvector to interface{} and a generated column rejects explicit
// writes (D3).
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (CreateJobRow, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.CompanyID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.WorkMode,
		arg.EmploymentType,
		arg.Seniority,
		arg.Location,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryCurrency,
	)
	var i CreateJobRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.WorkMode,
		&i.EmploymentType,
		&i.Seniority,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.CompanyName,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT
    j.id,
    j.title,
    j.description,
    j.location,
    j.work_mode,
    j.employment_type,
    j.seniority,
    j.salary_min,
    j.salary_max,
    j.salary_currency,
    j.status,
    j.published_at,
    j.deleted_at,
    c.id AS company_id,
    c.name AS company_name
FROM jobs j
JOIN companies c ON c.id = j.company_id
WHERE j.id = $1
  AND j.status = 'published'
  AND j.deleted_at IS NULL
  AND c.status = 'active'
`

type GetJobByIDRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Location       pgtype.Text        `json:"location"`
	WorkMode       string             `json:"work_mode"`
	EmploymentType string             `json:"employment_type"`
	Seniority      string             `json:"seniority"`
	SalaryMin      pgtype.Int4        `json:"salary_min"`
	SalaryMax      pgtype.Int4        `json:"salary_max"`
	SalaryCurrency string             `json:"salary_currency"`
	Status         string             `json:"status"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CompanyID      uuid.UUID          `json:"company_id"`
	CompanyName    string             `json:"company_name"`
}

// Public detail endpoint. Same visibility rule as SearchJobs, plus the
// positional `$1` id. Explicit column list keeps `search_vector` out of
// the scan and matches the embedded `{company: {id, name}}` shape.
func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (GetJobByIDRow, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i GetJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.WorkMode,
		&i.EmploymentType,
		&i.Seniority,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CompanyID,
		&i.CompanyName,
	)
	return i, err
}

const getJobForUpdate = `-- name: GetJobForUpdate :one
SELECT
    j.id,
    j.title,
    j.description,
    j.location,
    j.work_mode,
    j.employment_type,
    j.seniority,
    j.salary_min,
    j.salary_max,
    j.salary_currency,
    j.status,
    j.published_at,
    j.updated_at,
    j.company_id,
    c.name AS company_name
FROM jobs j
JOIN companies c ON c.id = j.company_id
WHERE j.id = $1
  AND j.company_id = $2
  AND j.deleted_at IS NULL
`

type GetJobForUpdateParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

type GetJobForUpdateRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Location       pgtype.Text        `json:"location"`
	WorkMode       string             `json:"work_mode"`
	EmploymentType string             `json:"employment_type"`
	Seniority      string             `json:"seniority"`
	SalaryMin      pgtype.Int4        `json:"salary_min"`
	SalaryMax      pgtype.Int4        `json:"salary_max"`
	SalaryCurrency string             `json:"salary_currency"`
	Status         string             `json:"status"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompanyID      uuid.UUID          `json:"company_id"`
	CompanyName    string             `json:"company_name"`
}

// Write-path read for the gated PATCH /jobs/{id} endpoint (design D3).
// NON-visibility-narrowed: the write path MUST see drafts (so a
// recruiter can publish them) and closed rows (so the use case can
// reject them with the terminal-rule 400). Only the company scope and
// `deleted_at IS NULL` apply.
//
// Joined to `companies` for `name` only - the editor view embeds
// `{id, name}` (design D7), so one round-trip is enough.
//
// The explicit column list keeps `search_vector` (STORED generated)
// and every other internal column OUT of the scan. `j.status` is
// included so the use case can run the transition table; `j.updated_at`
// so the use case can CAS-compare against `If-Unmodified-Since`.
func (q *Queries) GetJobForUpdate(ctx context.Context, arg GetJobForUpdateParams) (GetJobForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getJobForUpdate, arg.ID, arg.CompanyID)
	var i GetJobForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.WorkMode,
		&i.EmploymentType,
		&i.Seniority,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.CompanyName,
	)
	return i, err
}

const searchJobs = `-- name: SearchJobs :many
SELECT
    j.id,
    j.title,
    j.description,
    j.location,
    j.work_mode,
    j.employment_type,
    j.seniority,
    j.salary_min,
    j.salary_max,
    j.salary_currency,
    j.status,
    j.published_at,
    j.deleted_at,
    c.id AS company_id,
    c.name AS company_name,
    ts_rank(
        j.search_vector,
        websearch_to_tsquery('spanish', COALESCE($1::text, ''))
    ) AS search_rank
FROM jobs j
JOIN companies c ON c.id = j.company_id
WHERE j.status = 'published'
  AND j.deleted_at IS NULL
  AND c.status = 'active'
  AND ($1::text IS NULL
       OR j.search_vector @@ websearch_to_tsquery('spanish', $1::text))
  AND ($2::text IS NULL
       OR j.seniority = $2::text)
  AND ($3::text IS NULL
       OR j.work_mode = $3::text)
  AND ($4::text IS NULL
       OR j.employment_type = $4::text)
  AND ($5::text IS NULL
       OR j.location ILIKE '%' || $5::text || '%')
  AND ($6::text IS NULL
       OR j.salary_currency = $6::text)
  AND ($7::timestamptz IS NULL
       OR (ts_rank(
              j.search_vector,
              websearch_to_tsquery('spanish', COALESCE($1::text, ''))
           ),
           j.published_at,
           j.id)
          < (COALESCE($8::float8, 0),
             $7::timestamptz,
             $9::uuid))
ORDER BY search_rank DESC,
         j.published_at DESC,
         j.id DESC
LIMIT $10::int
`

type SearchJobsParams struct {
	Q              pgtype.Text        `json:"q"`
	Seniority      pgtype.Text        `json:"seniority"`
	WorkMode       pgtype.Text        `json:"work_mode"`
	EmploymentType pgtype.Text        `json:"employment_type"`
	Location       pgtype.Text        `json:"location"`
	SalaryCurrency pgtype.Text        `json:"salary_currency"`
	CursorTs       pgtype.Timestamptz `json:"cursor_ts"`
	CursorRank     pgtype.Float8      `json:"cursor_rank"`
	CursorID       pgtype.UUID        `json:"cursor_id"`
	Limit          pgtype.Int4        `json:"limit"`
}

type SearchJobsRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Location       pgtype.Text        `json:"location"`
	WorkMode       string             `json:"work_mode"`
	EmploymentType string             `json:"employment_type"`
	Seniority      string             `json:"seniority"`
	SalaryMin      pgtype.Int4        `json:"salary_min"`
	SalaryMax      pgtype.Int4        `json:"salary_max"`
	SalaryCurrency string             `json:"salary_currency"`
	Status         string             `json:"status"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CompanyID      uuid.UUID          `json:"company_id"`
	CompanyName    string             `json:"company_name"`
	SearchRank     float32            `json:"search_rank"`
}

// Public read listing for jobs (§spec/jobs). The visibility rule
// (§Read-Side Visibility Rule) is enforced here, not in Go: a row
// surfaces only when `jobs.status='published'`, `jobs.deleted_at IS NULL`,
// and the owning company is `active`. The column list is explicit (not
// `SELECT *`) so the STORED generated `search_vector` (sqlc would map it
// to `interface{}`) never enters the scan — every field on the row is
// typed (uuid.UUID, string, pgtype.Text, pgtype.Int4, pgtype.Timestamptz).
// `companies.{id,name}` are joined in the same query (zero extra round
// trip) to embed `{company: {id, name}}` in the API response.
//
// All optional inputs use `sqlc.narg` (nullable named params). When the
// adapter doesn't pass a value, the predicate degenerates to TRUE — the
// same query serves both search and browse modes without a branch in Go.
//
// FTS uses `websearch_to_tsquery` (safe parser; never throws on
// malformed input — matches spec scenario "malformed q does not 500").
// The tsquery is computed in WHERE and again in ORDER BY; Postgres CSEs
// it in the planner, so the cost is negligible. `COALESCE(..., ”)` on
// the ORDER BY side is what makes browse-mode safe: when `q` is NULL,
// `websearch_to_tsquery('spanish', ”)` yields an empty tsquery and
// `ts_rank` returns 0 for every row, degenerating the ORDER BY to
// `published_at DESC, id DESC` exactly as the spec requires.
//
// Keyset pagination (Decision 3): cursor = opaque base64url(JSON). When
// the adapter passes `cursor_ts` + `cursor_id`, the row-tuple predicate
// `(published_at, id) < (cursor_ts, cursor_id)` narrows to the next
// page; otherwise the predicate degenerates to TRUE (first page).
//
// `LIMIT @limit+1` from the adapter — the +1 row is dropped in Go and
// its presence signals "has more" (see Decision 3).
//
// Dropped `j.company_id` from the SELECT (redundant with
// `c.id AS company_id` via the JOIN on this same column — keeping it
// would produce two columns with the same output name, which sqlc
// cannot map to a single struct field) to keep all output column names
// unique. `j.status` and `j.deleted_at` are included so the adapter
// can assert visibility at the row level; they are not exposed in the
// API response per spec.
func (q *Queries) SearchJobs(ctx context.Context, arg SearchJobsParams) ([]SearchJobsRow, error) {
	rows, err := q.db.Query(ctx, searchJobs,
		arg.Q,
		arg.Seniority,
		arg.WorkMode,
		arg.EmploymentType,
		arg.Location,
		arg.SalaryCurrency,
		arg.CursorTs,
		arg.CursorRank,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchJobsRow
	for rows.Next() {
		var i SearchJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.WorkMode,
			&i.EmploymentType,
			&i.Seniority,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.Status,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.CompanyID,
			&i.CompanyName,
			&i.SearchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteJob = `-- name: SoftDeleteJob :one
WITH active AS (
    SELECT id
    FROM companies
    WHERE id = $1::uuid
      AND status = 'active'
),
upd AS (
    UPDATE jobs
    SET
        deleted_at = now(),
        updated_at = clock_timestamp()
    WHERE id         = $2::uuid
      AND company_id = $1::uuid
      AND deleted_at IS NULL
      AND updated_at = $3::timestamptz
      AND EXISTS (SELECT 1 FROM active)
    RETURNING id
)
SELECT
    EXISTS (SELECT 1 FROM active) AS guard_passed,
    (SELECT count(*) FROM upd)    AS deleted_count
`

type SoftDeleteJobParams struct {
	CompanyID uuid.UUID          `json:"company_id"`
	ID        uuid.UUID          `json:"id"`
	CasToken  pgtype.Timestamptz `json:"cas_token"`
}

type SoftDeleteJobRow struct {
	GuardPassed  bool  `json:"guard_passed"`
	DeletedCount int64 `json:"deleted_count"`
}

// Atomic soft-delete + CAS + active-company guard for DELETE /jobs/{id}
// (design D1/D2/D3, jobs-soft-delete slice).
//
// Minimal SET list: ONLY deleted_at = now() and updated_at = now().
// published_at / title / description / status / work_mode /
// employment_type / seniority / location / salary_min / salary_max /
// salary_currency are PRESERVED as audit history. search_vector (STORED
// generated) is naturally unchanged because its inputs (title,
// description) are not touched; the partial index jobs_public_listing_idx
// (predicated on deleted_at IS NULL) drops the row automatically.
//
// Active-company guard (mirrors UpdateJob D1):
//   - the `active` CTE selects the owning company ONLY when
//     companies.status = 'active'. suspended / pending_verification /
//     missing company yields zero rows in `active`, so the UPDATE inside
//     `upd` matches zero rows AND the final SELECT reports
//     guard_passed = false.
//   - the UPDATE's WHERE adds `AND EXISTS (SELECT 1 FROM active)` so the
//     guard and the write are the same statement — no TOCTOU window.
//
// Outcome matrix (adapter D2):
//
//	guard_passed = false, deleted_count = 0
//	  → ErrCompanyNotActive (suspended/pending/missing company)
//	guard_passed = true,  deleted_count = 0
//	  → ErrJobNotFound (CAS lost / already-soft-deleted / cross-company
//	    race with an active company; the use case already CAS-compared,
//	    so this is a residual tight race — mapped to 404, no re-read)
//	guard_passed = true,  deleted_count = 1
//	  → success (1 row tombstoned)
//
// CAS in the UPDATE WHERE: `updated_at = sqlc.arg('cas_token')` — the
// atomic race-free guard. The final scalar SELECT (no FROM, no WHERE)
// ALWAYS returns exactly one row, so pgx.ErrNoRows is unreachable via the
// designed flow (mapSoftDeleteError keeps it as defense-in-depth).
func (q *Queries) SoftDeleteJob(ctx context.Context, arg SoftDeleteJobParams) (SoftDeleteJobRow, error) {
	row := q.db.QueryRow(ctx, softDeleteJob, arg.CompanyID, arg.ID, arg.CasToken)
	var i SoftDeleteJobRow
	err := row.Scan(&i.GuardPassed, &i.DeletedCount)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
WITH active AS (
    SELECT id
    FROM companies
    WHERE id = $1::uuid
      AND status = 'active'
),
upd AS (
    UPDATE jobs
    SET
        title           = COALESCE($2::text,           title),
        description     = COALESCE($3::text,     description),
        work_mode       = COALESCE($4::text,       work_mode),
        employment_type = COALESCE($5::text, employment_type),
        seniority       = COALESCE($6::text,       seniority),
        salary_currency = COALESCE($7::text, salary_currency),
        location        = CASE WHEN $8::boolean
                                THEN $9::text
                                ELSE location END,
        salary_min      = CASE WHEN $10::boolean
                                THEN $11::int
                                ELSE salary_min END,
        salary_max      = CASE WHEN $12::boolean
                                THEN $13::int
                                ELSE salary_max END,
        status          = COALESCE($14::text, status),
        published_at    = CASE WHEN $14::text = 'published'
                                THEN COALESCE(published_at, now())
                                ELSE published_at END,
        updated_at      = clock_timestamp()
    WHERE id         = $15::uuid
      AND company_id = $1::uuid
      AND deleted_at IS NULL
      AND updated_at = $16::timestamptz
      AND EXISTS (SELECT 1 FROM active)
    RETURNING id
)
SELECT
    EXISTS (SELECT 1 FROM active) AS guard_passed,
    (SELECT count(*) FROM upd)    AS updated_count
`

type UpdateJobParams struct {
	CompanyID      uuid.UUID          `json:"company_id"`
	Title          pgtype.Text        `json:"title"`
	Description    pgtype.Text        `json:"description"`
	WorkMode       pgtype.Text        `json:"work_mode"`
	EmploymentType pgtype.Text        `json:"employment_type"`
	Seniority      pgtype.Text        `json:"seniority"`
	SalaryCurrency pgtype.Text        `json:"salary_currency"`
	SetLocation    bool               `json:"set_location"`
	Location       pgtype.Text        `json:"location"`
	SetSalaryMin   bool               `json:"set_salary_min"`
	SalaryMin      pgtype.Int4        `json:"salary_min"`
	SetSalaryMax   bool               `json:"set_salary_max"`
	SalaryMax      pgtype.Int4        `json:"salary_max"`
	Status         pgtype.Text        `json:"status"`
	ID             uuid.UUID          `json:"id"`
	CasToken       pgtype.Timestamptz `json:"cas_token"`
}

type UpdateJobRow struct {
	GuardPassed  bool  `json:"guard_passed"`
	UpdatedCount int64 `json:"updated_count"`
}

// Atomic partial update + CAS + active-company guard for PATCH /jobs/{id}
// (design D1/D2/D3, jobs-reopen slice).
//
// Three column-update shapes (unchanged from the pre-guard statement):
//   - COALESCE(sqlc.narg(...), col)  for the five closed-set + text
//     fields: nullable text param, default = column value (untouched).
//   - CASE WHEN sqlc.arg('set_<field>')::boolean THEN sqlc.narg(...)
//     ELSE col END  for the three nullable columns (location,
//     salary_min, salary_max): the boolean flag toggles "write this
//     column"; the value NULL clears, a real value sets.
//   - status = COALESCE(sqlc.narg('status')::text, status): nullable
//     text param, default = current column value.
//
// Side effect on `published_at` (atomic in the same statement so the
// `jobs_published_integrity_check` always holds):
//
//	  published_at = CASE WHEN sqlc.narg('status')::text = 'published'
//	                      THEN COALESCE(published_at, now())
//	                      ELSE published_at END
//	- draft -> published   : sets published_at = now() (was NULL).
//	- published -> published: preserves the existing published_at.
//	- published -> closed   : preserves the existing published_at.
//	- closed -> published   : preserves the existing published_at (D6
//	                          — audit history; the row was previously
//	                          published, so published_at is non-NULL
//	                          and COALESCE keeps it).
//	- any other transition : leaves published_at alone.
//
// Active-company guard (D1/D2):
//   - The `active` CTE selects the owning company ONLY when
//     companies.status = 'active'. A suspended / pending_verification
//     / missing company yields zero rows in `active`, so the UPDATE
//     inside `upd` matches zero rows AND the final SELECT reports
//     guard_passed = false.
//   - The UPDATE's WHERE clause adds `AND EXISTS (SELECT 1 FROM active)`
//     so the guard and the write are the same statement — no TOCTOU
//     window between a separate check and the UPDATE.
//   - The final scalar SELECT returns
//     `EXISTS (SELECT 1 FROM active) AS guard_passed,
//     (SELECT count(*) FROM upd) AS updated_count`
//     so the adapter can distinguish:
//     guard_passed = false, updated_count = 0
//     → ErrCompanyNotActive (suspended/pending/missing company)
//     guard_passed = true,  updated_count = 0
//     → ErrJobNotFound (CAS lost / cross-company / soft-delete race
//     with active company — D3; use case re-reads)
//     guard_passed = true,  updated_count = 1
//     → success (1 row affected)
//
// CAS in the UPDATE WHERE: `updated_at = sqlc.arg('cas_token')` -
// the atomic race-free guard for the row predicates
// (id, company_id, deleted_at IS NULL). Two writers holding the same
// CAS: only one UPDATE returns 1 row in `upd`; the other returns 0.
//
// The final SELECT is scalar (no FROM, no WHERE), so it ALWAYS returns
// exactly one row. `pgx.ErrNoRows` is therefore unreachable via the
// designed flow — the `pgx.ErrNoRows → ErrCompanyNotActive` branch in
// `mapUpdateError` is defense-in-depth (mirrors `mapCreateError`).
//
// Never touched: search_vector (STORED generated), company_id,
// created_at, id, deleted_at.
func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (UpdateJobRow, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.WorkMode,
		arg.EmploymentType,
		arg.Seniority,
		arg.SalaryCurrency,
		arg.SetLocation,
		arg.Location,
		arg.SetSalaryMin,
		arg.SalaryMin,
		arg.SetSalaryMax,
		arg.SalaryMax,
		arg.Status,
		arg.ID,
		arg.CasToken,
	)
	var i UpdateJobRow
	err := row.Scan(&i.GuardPassed, &i.UpdatedCount)
	return i, err
}
