// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getJobByID = `-- name: GetJobByID :one
SELECT
    j.id,
    j.title,
    j.description,
    j.location,
    j.work_mode,
    j.employment_type,
    j.seniority,
    j.salary_min,
    j.salary_max,
    j.salary_currency,
    j.status,
    j.published_at,
    j.deleted_at,
    c.id AS company_id,
    c.name AS company_name
FROM jobs j
JOIN companies c ON c.id = j.company_id
WHERE j.id = $1
  AND j.status = 'published'
  AND j.deleted_at IS NULL
  AND c.status = 'active'
`

type GetJobByIDRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Location       pgtype.Text        `json:"location"`
	WorkMode       string             `json:"work_mode"`
	EmploymentType string             `json:"employment_type"`
	Seniority      string             `json:"seniority"`
	SalaryMin      pgtype.Int4        `json:"salary_min"`
	SalaryMax      pgtype.Int4        `json:"salary_max"`
	SalaryCurrency string             `json:"salary_currency"`
	Status         string             `json:"status"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CompanyID      uuid.UUID          `json:"company_id"`
	CompanyName    string             `json:"company_name"`
}

// Public detail endpoint. Same visibility rule as SearchJobs, plus the
// positional `$1` id. Explicit column list keeps `search_vector` out of
// the scan and matches the embedded `{company: {id, name}}` shape.
func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (GetJobByIDRow, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i GetJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.WorkMode,
		&i.EmploymentType,
		&i.Seniority,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CompanyID,
		&i.CompanyName,
	)
	return i, err
}

const searchJobs = `-- name: SearchJobs :many
SELECT
    j.id,
    j.title,
    j.description,
    j.location,
    j.work_mode,
    j.employment_type,
    j.seniority,
    j.salary_min,
    j.salary_max,
    j.salary_currency,
    j.status,
    j.published_at,
    j.deleted_at,
    c.id AS company_id,
    c.name AS company_name,
    ts_rank(
        j.search_vector,
        websearch_to_tsquery('spanish', COALESCE($1::text, ''))
    ) AS search_rank
FROM jobs j
JOIN companies c ON c.id = j.company_id
WHERE j.status = 'published'
  AND j.deleted_at IS NULL
  AND c.status = 'active'
  AND ($1::text IS NULL
       OR j.search_vector @@ websearch_to_tsquery('spanish', $1::text))
  AND ($2::text IS NULL
       OR j.seniority = $2::text)
  AND ($3::text IS NULL
       OR j.work_mode = $3::text)
  AND ($4::text IS NULL
       OR j.employment_type = $4::text)
  AND ($5::text IS NULL
       OR j.location ILIKE '%' || $5::text || '%')
  AND ($6::text IS NULL
       OR j.salary_currency = $6::text)
  AND ($7::timestamptz IS NULL
       OR (ts_rank(
              j.search_vector,
              websearch_to_tsquery('spanish', COALESCE($1::text, ''))
           ),
           j.published_at,
           j.id)
          < (COALESCE($8::float8, 0),
             $7::timestamptz,
             $9::uuid))
ORDER BY search_rank DESC,
         j.published_at DESC,
         j.id DESC
LIMIT $10::int
`

type SearchJobsParams struct {
	Q              pgtype.Text        `json:"q"`
	Seniority      pgtype.Text        `json:"seniority"`
	WorkMode       pgtype.Text        `json:"work_mode"`
	EmploymentType pgtype.Text        `json:"employment_type"`
	Location       pgtype.Text        `json:"location"`
	SalaryCurrency pgtype.Text        `json:"salary_currency"`
	CursorTs       pgtype.Timestamptz `json:"cursor_ts"`
	CursorRank     pgtype.Float8      `json:"cursor_rank"`
	CursorID       pgtype.UUID        `json:"cursor_id"`
	Limit          pgtype.Int4        `json:"limit"`
}

type SearchJobsRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Location       pgtype.Text        `json:"location"`
	WorkMode       string             `json:"work_mode"`
	EmploymentType string             `json:"employment_type"`
	Seniority      string             `json:"seniority"`
	SalaryMin      pgtype.Int4        `json:"salary_min"`
	SalaryMax      pgtype.Int4        `json:"salary_max"`
	SalaryCurrency string             `json:"salary_currency"`
	Status         string             `json:"status"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CompanyID      uuid.UUID          `json:"company_id"`
	CompanyName    string             `json:"company_name"`
	SearchRank     float32            `json:"search_rank"`
}

// Public read listing for jobs (§spec/jobs). The visibility rule
// (§Read-Side Visibility Rule) is enforced here, not in Go: a row
// surfaces only when `jobs.status='published'`, `jobs.deleted_at IS NULL`,
// and the owning company is `active`. The column list is explicit (not
// `SELECT *`) so the STORED generated `search_vector` (sqlc would map it
// to `interface{}`) never enters the scan — every field on the row is
// typed (uuid.UUID, string, pgtype.Text, pgtype.Int4, pgtype.Timestamptz).
// `companies.{id,name}` are joined in the same query (zero extra round
// trip) to embed `{company: {id, name}}` in the API response.
//
// All optional inputs use `sqlc.narg` (nullable named params). When the
// adapter doesn't pass a value, the predicate degenerates to TRUE — the
// same query serves both search and browse modes without a branch in Go.
//
// FTS uses `websearch_to_tsquery` (safe parser; never throws on
// malformed input — matches spec scenario "malformed q does not 500").
// The tsquery is computed in WHERE and again in ORDER BY; Postgres CSEs
// it in the planner, so the cost is negligible. `COALESCE(..., ”)` on
// the ORDER BY side is what makes browse-mode safe: when `q` is NULL,
// `websearch_to_tsquery('spanish', ”)` yields an empty tsquery and
// `ts_rank` returns 0 for every row, degenerating the ORDER BY to
// `published_at DESC, id DESC` exactly as the spec requires.
//
// Keyset pagination (Decision 3): cursor = opaque base64url(JSON). When
// the adapter passes `cursor_ts` + `cursor_id`, the row-tuple predicate
// `(published_at, id) < (cursor_ts, cursor_id)` narrows to the next
// page; otherwise the predicate degenerates to TRUE (first page).
//
// `LIMIT @limit+1` from the adapter — the +1 row is dropped in Go and
// its presence signals "has more" (see Decision 3).
//
// Dropped `j.company_id` from the SELECT (redundant with
// `c.id AS company_id` via the JOIN on this same column — keeping it
// would produce two columns with the same output name, which sqlc
// cannot map to a single struct field) to keep all output column names
// unique. `j.status` and `j.deleted_at` are included so the adapter
// can assert visibility at the row level; they are not exposed in the
// API response per spec.
func (q *Queries) SearchJobs(ctx context.Context, arg SearchJobsParams) ([]SearchJobsRow, error) {
	rows, err := q.db.Query(ctx, searchJobs,
		arg.Q,
		arg.Seniority,
		arg.WorkMode,
		arg.EmploymentType,
		arg.Location,
		arg.SalaryCurrency,
		arg.CursorTs,
		arg.CursorRank,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchJobsRow
	for rows.Next() {
		var i SearchJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.WorkMode,
			&i.EmploymentType,
			&i.Seniority,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.Status,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.CompanyID,
			&i.CompanyName,
			&i.SearchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
