// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CandidateLanguage struct {
	UserID   uuid.UUID `json:"user_id"`
	Language string    `json:"language"`
	Level    string    `json:"level"`
}

type CandidateProfile struct {
	UserID               uuid.UUID          `json:"user_id"`
	Phone                pgtype.Text        `json:"phone"`
	LinkedinUrl          pgtype.Text        `json:"linkedin_url"`
	PortfolioUrl         pgtype.Text        `json:"portfolio_url"`
	ProfessionalTitle    pgtype.Text        `json:"professional_title"`
	CurrentCompany       pgtype.Text        `json:"current_company"`
	YearsOfExperience    pgtype.Int2        `json:"years_of_experience"`
	ProfileSummary       pgtype.Text        `json:"profile_summary"`
	BirthDate            pgtype.Date        `json:"birth_date"`
	City                 pgtype.Text        `json:"city"`
	Country              pgtype.Text        `json:"country"`
	EducationLevel       pgtype.Text        `json:"education_level"`
	FieldOfStudy         pgtype.Text        `json:"field_of_study"`
	Skills               []string           `json:"skills"`
	CurrentSalaryGross   pgtype.Int4        `json:"current_salary_gross"`
	CurrentSalaryNet     pgtype.Int4        `json:"current_salary_net"`
	ExpectedSalary       pgtype.Int4        `json:"expected_salary"`
	SalaryCurrency       string             `json:"salary_currency"`
	ExpectedSalaryPeriod pgtype.Text        `json:"expected_salary_period"`
	CvS3Key              pgtype.Text        `json:"cv_s3_key"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	SearchVector         interface{}        `json:"search_vector"`
}

type Company struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Rfc           string             `json:"rfc"`
	IndustryID    string             `json:"industry_id"`
	Website       pgtype.Text        `json:"website"`
	LogoUrl       pgtype.Text        `json:"logo_url"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	Description   pgtype.Text        `json:"description"`
	Size          pgtype.Text        `json:"size"`
	FoundedYear   pgtype.Int2        `json:"founded_year"`
	City          pgtype.Text        `json:"city"`
	Country       pgtype.Text        `json:"country"`
	LinkedinUrl   pgtype.Text        `json:"linkedin_url"`
	InstagramUrl  pgtype.Text        `json:"instagram_url"`
	FacebookUrl   pgtype.Text        `json:"facebook_url"`
	TwitterUrl    pgtype.Text        `json:"twitter_url"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
}

type Industry struct {
	ID        string             `json:"id"`
	LabelEs   string             `json:"label_es"`
	LabelEn   string             `json:"label_en"`
	SortOrder int32              `json:"sort_order"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID             uuid.UUID          `json:"id"`
	CompanyID      uuid.UUID          `json:"company_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	WorkMode       string             `json:"work_mode"`
	EmploymentType string             `json:"employment_type"`
	Seniority      string             `json:"seniority"`
	Status         string             `json:"status"`
	Location       pgtype.Text        `json:"location"`
	SalaryMin      pgtype.Int4        `json:"salary_min"`
	SalaryMax      pgtype.Int4        `json:"salary_max"`
	SalaryCurrency string             `json:"salary_currency"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	SearchVector   interface{}        `json:"search_vector"`
}

type User struct {
	ID         uuid.UUID          `json:"id"`
	CognitoSub string             `json:"cognito_sub"`
	Email      string             `json:"email"`
	FullName   string             `json:"full_name"`
	UserType   string             `json:"user_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}
