// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error)
	ListActiveIndustries(ctx context.Context) ([]Industry, error)
}

var _ Querier = (*Queries)(nil)
