// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	// Adds a row to `company_members`. UNIQUE(user_id) means a second insert with
	// the same user_id surfaces SQLSTATE 23505 to the adapter (mapped to
	// ErrMemberExists in the companies/infrastructure layer); FK violations on
	// user_id / company_id surface SQLSTATE 23503 (mapped to ErrUserNotFound /
	// ErrCompanyNotFound).
	CreateCompanyMember(ctx context.Context, arg CreateCompanyMemberParams) (CompanyMember, error)
	// Idempotent upsert keyed on the partial unique index `users_cognito_sub_unique`.
	// The `WHERE deleted_at IS NULL` predicate is required: a bare `ON CONFLICT (cognito_sub)`
	// would not match the partial index and would raise SQLSTATE 42P10.
	// On conflict, `RETURNING *` produces zero rows so pgx returns pgx.ErrNoRows;
	// the adapter re-fetches by cognito_sub to return the existing entity.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCandidateLanguagesByUserID(ctx context.Context, userID uuid.UUID) error
	GetCandidateProfileByUserID(ctx context.Context, userID uuid.UUID) (CandidateProfile, error)
	GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error)
	// Public detail endpoint. Same visibility rule as SearchJobs, plus the
	// positional `$1` id. Explicit column list keeps `search_vector` out of
	// the scan and matches the embedded `{company: {id, name}}` shape.
	GetJobByID(ctx context.Context, id uuid.UUID) (GetJobByIDRow, error)
	// Single membership lookup for the membership-resolver chain
	// (`sub → users.id → company_members`) — see design D6. Returns
	// pgx.ErrNoRows when the user has no membership, which the service maps to
	// ErrNotAMember.
	GetMembershipByUserID(ctx context.Context, userID uuid.UUID) (CompanyMember, error)
	GetUserByCognitoSub(ctx context.Context, cognitoSub string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Used inside the atomic replace transaction. Composite PK (user_id, language)
	// prevents duplicate languages for the same user — the adapter surfaces a
	// 23505 as ErrDuplicateLanguage.
	InsertCandidateLanguage(ctx context.Context, arg InsertCandidateLanguageParams) error
	ListActiveIndustries(ctx context.Context) ([]Industry, error)
	// All members of a company (GET /me/company/members). Ordered by created_at
	// for stable rendering; backed by the `company_members_company_id_idx` B-tree.
	ListByCompanyID(ctx context.Context, companyID uuid.UUID) ([]CompanyMember, error)
	ListCandidateLanguagesByUserID(ctx context.Context, userID uuid.UUID) ([]CandidateLanguage, error)
	// Same-company guard (design D7) — see UpdateMemberRole for rationale.
	// HARD DELETE (design D2) frees `user_id` for re-assignment.
	RemoveCompanyMember(ctx context.Context, arg RemoveCompanyMemberParams) (int64, error)
	// Public read listing for jobs (§spec/jobs). The visibility rule
	// (§Read-Side Visibility Rule) is enforced here, not in Go: a row
	// surfaces only when `jobs.status='published'`, `jobs.deleted_at IS NULL`,
	// and the owning company is `active`. The column list is explicit (not
	// `SELECT *`) so the STORED generated `search_vector` (sqlc would map it
	// to `interface{}`) never enters the scan — every field on the row is
	// typed (uuid.UUID, string, pgtype.Text, pgtype.Int4, pgtype.Timestamptz).
	// `companies.{id,name}` are joined in the same query (zero extra round
	// trip) to embed `{company: {id, name}}` in the API response.
	//
	// All optional inputs use `sqlc.narg` (nullable named params). When the
	// adapter doesn't pass a value, the predicate degenerates to TRUE — the
	// same query serves both search and browse modes without a branch in Go.
	//
	// FTS uses `websearch_to_tsquery` (safe parser; never throws on
	// malformed input — matches spec scenario "malformed q does not 500").
	// The tsquery is computed in WHERE and again in ORDER BY; Postgres CSEs
	// it in the planner, so the cost is negligible. `COALESCE(..., '')` on
	// the ORDER BY side is what makes browse-mode safe: when `q` is NULL,
	// `websearch_to_tsquery('spanish', '')` yields an empty tsquery and
	// `ts_rank` returns 0 for every row, degenerating the ORDER BY to
	// `published_at DESC, id DESC` exactly as the spec requires.
	//
	// Keyset pagination (Decision 3): cursor = opaque base64url(JSON). When
	// the adapter passes `cursor_ts` + `cursor_id`, the row-tuple predicate
	// `(published_at, id) < (cursor_ts, cursor_id)` narrows to the next
	// page; otherwise the predicate degenerates to TRUE (first page).
	//
	// `LIMIT @limit+1` from the adapter — the +1 row is dropped in Go and
	// its presence signals "has more" (see Decision 3).
	//
	// Dropped `j.company_id` from the SELECT (redundant with
	// `c.id AS company_id` via the JOIN on this same column — keeping it
	// would produce two columns with the same output name, which sqlc
	// cannot map to a single struct field) to keep all output column names
	// unique. `j.status` and `j.deleted_at` are included so the adapter
	// can assert visibility at the row level; they are not exposed in the
	// API response per spec.
	SearchJobs(ctx context.Context, arg SearchJobsParams) ([]SearchJobsRow, error)
	// Same-company guard (design D7): the SQL predicate
	// `id = $1 AND company_id = $2` is the race-free, IDOR-proof boundary for
	// UpdateRole. 0 rows affected → ErrMemberNotFound in the adapter.
	// `updated_at` is touched here so downstream callers never have to remember
	// to do it.
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (int64, error)
	// Idempotent upsert keyed on the PK (user_id). First PUT creates the row;
	// subsequent PUTs overwrite the editable columns. search_vector is a STORED
	// generated column owned by Postgres and MUST NOT be touched here.
	UpsertCandidateProfile(ctx context.Context, arg UpsertCandidateProfileParams) (CandidateProfile, error)
}

var _ Querier = (*Queries)(nil)
