// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, cognito_sub, email, full_name, user_type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (cognito_sub) WHERE deleted_at IS NULL DO NOTHING
RETURNING id, cognito_sub, email, full_name, user_type, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID         uuid.UUID `json:"id"`
	CognitoSub string    `json:"cognito_sub"`
	Email      string    `json:"email"`
	FullName   string    `json:"full_name"`
	UserType   string    `json:"user_type"`
}

// Idempotent upsert keyed on the partial unique index `users_cognito_sub_unique`.
// The `WHERE deleted_at IS NULL` predicate is required: a bare `ON CONFLICT (cognito_sub)`
// would not match the partial index and would raise SQLSTATE 42P10.
// On conflict, `RETURNING *` produces zero rows so pgx returns pgx.ErrNoRows;
// the adapter re-fetches by cognito_sub to return the existing entity.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.CognitoSub,
		arg.Email,
		arg.FullName,
		arg.UserType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.FullName,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByCognitoSub = `-- name: GetUserByCognitoSub :one
SELECT id, cognito_sub, email, full_name, user_type, created_at, updated_at, deleted_at FROM users
WHERE cognito_sub = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByCognitoSub(ctx context.Context, cognitoSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByCognitoSub, cognitoSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.FullName,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, cognito_sub, email, full_name, user_type, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.FullName,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
